### ISSUE TITLE
How to create Org VDC Networks?

### ISSUE THREAD

**Issue by urajio** [vmware/ansible-module-vcloud-director#10]
How to create Org VDC Networks?

**Comment by mukultaneja** [comment]
Hi @urajio 
We are currently working on the networking modules. I will keep you posted once the development will be done!

**Comment by rackergs** [comment]
Any chance you could do this in a public branch? The network piece is a pending automation item for us and if we could test/contribute I'd like to

**Comment by MichalTaratuta** [comment]
@urajio @rackergs @mukultaneja have a look at PR #36
