### ISSUE TITLE
vCD Ansible module documentation

### ISSUE THREAD

**Issue by mukultaneja** [vmware/ansible-module-vcloud-director#107]
For any successful product, documentation is a key item that helps the user to understand how to use the product better. We would really appreciate it if we can get help/suggestions on improving the documentation of vCD Ansible modules.

**Comment by surfer190** [comment]
Could I suggest that we stop using jekyll for docs and rather just keep a number of markdown files in the docs folder.
Or perhaps using the wiki in this github repo.

I think people want an instantaneous way of viewing the docs.

**Comment by mukultaneja** [comment]
thanks, @surfer190. I have updated the wiki of the repository. Please take a look and feel free to share your feedback!
