### ISSUE TITLE
problem creating a vapp 

### ISSUE THREAD

**Issue by MartinEtcheverry** [vmware/ansible-module-vcloud-director#11]
running this playbook 
`name: vCloudDirectorAnsible
  hosts: localhost
  environment:
    env_user: ansible_test       ## default user details for entire execution enviornment. Modules will use 
    env_password: Password   ## these default values in case no module level user details are provided.
    env_host: vcloud_Server_ip
    env_org: Prueba-001
    env_api_version: 29.0
    env_verify_ssl_certs: false

 
  tasks:
   - name: "create vapp"
     vcd_vapp:
        vapp_name: "test_vapp_ansible"
        template_name: "test_ansible_template"
        catalog_name: "Prueba"
        vdc: "Prueba-001"
        description: "test_description"
        network: "APP_10.233.1.0_27"
        fence_mode: "bridged"
        ip_allocation_mode: 'static'
        deploy: true
        power_on: true
        accept_all_eulas: true
        memory: 1024000
        cpu: 1000
        disk_size: 10240000
        password: "password"
        cust_script: "test_script"
        vm_name: "test_vm_ansible"
        hostname: "test_host"
        ip_address: "1.1.1.1"
        storage_profile: "Standard"
        network_adapter_type: "VMXNET3"
        state: "present"`

i get this error 
  `ansible-playbook test_e.yml
 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'

PLAY [vCloudDirectorAnsible] ***************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [create vapp] *************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/home/martin/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_9pbtjgbn/ansible_modlib.zip/ansible/module_utils/vcd.py\", line 45, in login\n  File \"/home/martin/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py\", line 724, in set_credentials\n    raise VcdException('Login failed.')\npyvcloud.vcd.exceptions.VcdException: Login failed.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/tmp/ansible_9pbtjgbn/ansible_module_vcd_vapp.py\", line 408, in <module>\n    main()\n  File \"/tmp/ansible_9pbtjgbn/ansible_module_vcd_vapp.py\", line 390, in main\n    module = Vapp(argument_spec=argument_spec, supports_check_mode=True)\n  File \"/tmp/ansible_9pbtjgbn/ansible_module_vcd_vapp.py\", line 213, in __init__\n    super(Vapp, self).__init__(**kwargs)\n  File \"/tmp/ansible_9pbtjgbn/ansible_modlib.zip/ansible/module_utils/vcd.py\", line 31, in __init__\n  File \"/tmp/ansible_9pbtjgbn/ansible_modlib.zip/ansible/module_utils/vcd.py\", line 49, in login\nansible.module_utils.vcd_errors.VCDLoginError: Login failed for user ansible_test to org Prueba-001\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/home/martin/ansible-module-vcloud-director/test_e.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1  `

NOTE - with the same authentication values i could create a catalog without problems.

Thanks in advance.
                                Martin

**Comment by MartinEtcheverry** [comment]
i think is earlier : line 45, in login\n File "/home/martin/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 724, in set_credentials\n raise VcdException('Login failed.')\npyvcloud.vcd.exceptions.VcdException: Login failed.

**Comment by mukultaneja** [comment]
Hi Martin,

Thanks for raising the concern.  I have added a new patch to resolve the issue. Please pull the latest code and try with the latest configuration,

https://github.com/vmware/ansible-module-vcloud-director/blob/master/docs/index.md#create-vapp

**Comment by mukultaneja** [comment]
Please share the VCD version you are using!

**Comment by ivanmpk** [comment]
Hi MAC,

-VCD 8.0.2
-Python 3.6.5
-Ansible 2.5.2
-Pyvcloud 19.3

**Comment by mukultaneja** [comment]
Hi @ivanmpk,

Thanks for sharing the information. I would like to tell you these Ansible modules are based on Pyvcloud and current Pyvcloud versions such as 27.0/28.0/29.0/30.0 support VCD versions 8.2/9/0/9.1 only. So you have to upgrade VCD version to use these modules.
