### ISSUE TITLE
Can't create VM in VCD

### ISSUE THREAD

**Issue by 1230394** [vmware/ansible-module-vcloud-director#111]
Hi,

we are not able to create a new vm via ansible in vcd. 

ansible 2.9.4
python version = 3.7.6 
env_api_version: 31.0 and 30.0 tried. 

vcloud Director version: 9.5

If we use the role: vappvm
with following customized values

- name: create vapp vm "{{ vapp_vm_1 }}" from catalog
  no_log: False
  vcd_vapp_vm:
    target_vm_name: "dev-test-08"
    target_vapp: "test_vapp_1"
    source_vdc: "vdc_name123"
   target_vdc: "vdc_name123"
    source_catalog_name: "Catalog_name123"
    source_template_name: "ubuntu-1804-amd64-opm"
    source_vm_name: "test123"
    hostname: "dev-test-09"
    vmpassword: "rootpass" 
    vmpassword_auto: "false"
    vmpassword_reset: "false"
    ip_allocation_mode: "DHCP"
    state: "present"
    power_on: "true"
    all_eulas_accepted: "true"
   storage_profile: "Perfomance"
    network: "web2Network"
  register: output

we got the following error:

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/var/folders/jh/2w5w6zb541q0pmt37j_30p7r0000gn/T/ansible_vcd_vapp_vm_payload_vonas3ua/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py:353: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.\nTraceback (most recent call last):\n  File \"/var/folders/jh/2w5w6zb541q0pmt37j_30p7r0000gn/T/ansible_vcd_vapp_vm_payload_vonas3ua/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 338, in add_vm\n  File \"/var/folders/jh/2w5w6zb541q0pmt37j_30p7r0000gn/T/ansible_vcd_vapp_vm_payload_vonas3ua/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 313, in get_vm\n  File \"/usr/local/lib/python3.7/site-packages/pyvcloud/vcd/vapp.py\", line 659, in get_vm\n    raise EntityNotFoundException('Can\\'t find VM \\'%s\\'' % vm_name)\npyvcloud.vcd.exceptions.EntityNotFoundException: Can't find VM 'dev-test-08'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/folders/jh/2w5w6zb541q0pmt37j_30p7r0000gn/T/ansible_vcd_vapp_vm_payload_vonas3ua/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 569, in main\n  File \"/var/folders/jh/2w5w6zb541q0pmt37j_30p7r0000gn/T/ansible_vcd_vapp_vm_payload_vonas3ua/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 237, in manage_states\n  File \"/var/folders/jh/2w5w6zb541q0pmt37j_30p7r0000gn/T/ansible_vcd_vapp_vm_payload_vonas3ua/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 356, in add_vm\n  File \"/var/folders/jh/2w5w6zb541q0pmt37j_30p7r0000gn/T/ansible_vcd_vapp_vm_payload_vonas3ua/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 310, in get_storage_profile\n  File \"/usr/local/lib/python3.7/site-packages/pyvcloud/vcd/vdc.py\", line 957, in get_storage_profile\n    'Storage Profile named \\'%s\\' not found' % profile_name)\npyvcloud.vcd.exceptions.EntityNotFoundException: Storage Profile named 'Perfomance' not found\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/Users/username/.ansible/tmp/ansible-tmp-1585222140.1346078-168389205116326/AnsiballZ_vcd_vapp_vm.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/Users/username/.ansible/tmp/ansible-tmp-1585222140.1346078-168389205116326/AnsiballZ_vcd_vapp_vm.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/username/.ansible/tmp/ansible-tmp-1585222140.1346078-168389205116326/AnsiballZ_vcd_vapp_vm.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.vcd_vapp_vm', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/var/folders/jh/2w5w6zb541q0pmt37j_30p7r0000gn/T/ansible_vcd_vapp_vm_payload_vonas3ua/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 583, in <module>\n  File \"/var/folders/jh/2w5w6zb541q0pmt37j_30p7r0000gn/T/ansible_vcd_vapp_vm_payload_vonas3ua/ansible_vcd_vapp_vm_payload.zip/ansible/modules/vcd_vapp_vm.py\", line 577, in main\n  File \"/var/folders/jh/2w5w6zb541q0pmt37j_30p7r0000gn/T/ansible_vcd_vapp_vm_payload_vonas3ua/ansible_vcd_vapp_vm_payload.zip/ansible/module_utils/basic.py\", line 2093, in fail_json\n  File \"/var/folders/jh/2w5w6zb541q0pmt37j_30p7r0000gn/T/ansible_vcd_vapp_vm_payload_vonas3ua/ansible_vcd_vapp_vm_payload.zip/ansible/module_utils/basic.py\", line 2065, in _return_formatted\n  File \"/var/folders/jh/2w5w6zb541q0pmt37j_30p7r0000gn/T/ansible_vcd_vapp_vm_payload_vonas3ua/ansible_vcd_vapp_vm_payload.zip/ansible/module_utils/basic.py\", line 418, in remove_values\n  File \"/var/folders/jh/2w5w6zb541q0pmt37j_30p7r0000gn/T/ansible_vcd_vapp_vm_payload_vonas3ua/ansible_vcd_vapp_vm_payload.zip/ansible/module_utils/basic.py\", line 401, in _remove_values_conditions\nTypeError: Value of unknown type: <class 'pyvcloud.vcd.exceptions.EntityNotFoundException'>, Storage Profile named 'Perfomance' not found\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

if the vm: dev-test-08 is in vcloud present then i got: VM is already present:
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "all_eulas_accepted": true,
            "api_version": "31.0",
            "cores_per_socket": null,
            "cust_script": "1",
            "deploy": false,
            "host": "vcloud-host",
            "hostname": "vcdcell",
            "ip_allocation_mode": "DHCP",
            "memory": null,
            "network": "web2Network",
            "operation": null,
            "org": "orgname",
            "password": "password",
            "power_on": false,
            "properties": null,
            "source_catalog_name": null,
            "source_template_name": null,
            "source_vapp": "test_vapp_1",
            "source_vdc": "vdc_name123",
            "source_vm_name": "dev-test-08",
            "state": "present",
            "storage_profile": "Perfomance",
            "target_vapp": "test_vapp_1",
            "target_vdc": "vdc_name123",
            "target_vm_name": "dev-test-08",
            "user": "username",
            "verify_ssl_certs": true,
            "virtual_cpus": null,
            "vmpassword": "rootpass",
            "vmpassword_auto": false,
            "vmpassword_reset": false
        }
    }
}

Can you support us?

**Comment by kaneda-fr** [comment]
Looking at the error trace, it looks like there is an issue with the storage profile name. Can you double check that storage "Perfomance" is available in that VDC.

**Comment by danielc256** [comment]
Hello,

Someone with this same problem? I'm facing the same issue, I try to create the VM and it says that the VM was not found, but it should create and not find if the name exists or not!

My role is exactly the same used above, however I'm not inputing the storage profile name, it's not required
