### ISSUE TITLE
Edge can not be updated

### ISSUE THREAD

**Issue by inetman28** [vmware/ansible-module-vcloud-director#114]
Hi,

**DESCRIPTION:**

I offer you add new feature in your ansible-modules. It feature should be update EDGE ip-range pool.

**CAUSE**:

I want to add new ip-range for the edge but edge not changed. 

For example, I already have a edge named like "EDGE-t.testov". For it EDGE ip-pool has been applied before: 10.0.0.99-10.0.0.99. Now, I want to update edge configuration to add new ip range 10.0.0.190-10.0.0.196 but output get me infromation that edge have not be changed:
```
ok: [localhost] => {
    "edgeupdate": {
        "changed": true,
        "failed": false,
        "msg": "Edge Gateway EDGE-t.testov has been updated with None"
    }
}
```

My play:
```
    - name: test to update edge
      vcd_vdc_gateway:
        gateway_name: "EDGE-t.testov"
        org_name: "t.testov"
        api_version: "32.0"
        vdc_name: "VDC-t.testov"
        #org: System
        ext_net_to_subnet_with_ip_range: {
          'EXT-MAIN-NET-10.0.0.0[22]': {
            '10.0.0.1/22': [
              "10.0.0.99-10.0.0.99",
              "10.0.0.190-10.0.0.196"
              ]
          }
        }
        state: update
      register: edgeupdate
      tags:
        - update1
```

**Comment by inetman28** [comment]
any ideas?

**Comment by mukultaneja** [comment]
@inetman28, as of now module does not cover the update of gateway IP ranges. So far we can only update gateway name, description, and HA state of the gateway using the module.

**Comment by inetman28** [comment]
> Feel free to raise an issue for this requirement.

How I can do that?

**Comment by mukultaneja** [comment]
you can update this issue only with your requirement regarding the edge gateway update process.

**Comment by inetman28** [comment]
> you can update this issue only with your requirement regarding the edge gateway update process.

updated

**Comment by mukultaneja** [comment]
@inetman28, I just added a patch to avail an operation on the edge gateway to update subnet ip pool ranges. Please try it out and feel free to open the issue again. I have also added a [wiki](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-Edge-Gateway) for the edge gateway module.
