### ISSUE TITLE
vCloud Director version: 10.0.0.14636284 

### ISSUE THREAD

**Issue by anudeep404** [vmware/ansible-module-vcloud-director#115]
I've been able to use this on vCD 9.x, recently we have upgraded to vCloud Director version: 10.0.0.14636284 
Would like to know if this is supported, ever since we upgraded, esxi deployment fails with the following error.

`failed: [localhost] (item={'name': 'esxi-01', 'mgmt_ip': '192.168.0.151', 'major_version': '67ga', 'patch_build': 11675023, 'cpu': 12, 'cores_per_cpu': 2, 'memory': 65536, 'cluster': 'Infra', 'datacenter': 'NSX_LAB'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "cluster": "Infra",
        "cores_per_cpu": 2,
        "cpu": 12,
        "datacenter": "NSX_LAB",
        "major_version": "67ga",
        "memory": 65536,
        "mgmt_ip": "192.168.0.151",
        "name": "esxi-01",
        "patch_build": 11675023
    },
    "module_stderr": "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_vcd_vapp_vm_payload_lp3uvkx9/__main__.py\", line 570, in main\n  File \"/tmp/ansible_vcd_vapp_vm_payload_lp3uvkx9/__main__.py\", line 237, in manage_states\n  File \"/tmp/ansible_vcd_vapp_vm_payload_lp3uvkx9/__main__.py\", line 319, in add_vm\n  File \"/tmp/ansible_vcd_vapp_vm_payload_lp3uvkx9/__main__.py\", line 286, in get_source_resource\n  File \"/usr/local/lib/python3.6/dist-packages/pyvcloud/vcd/org.py\", line 302, in get_catalog_item\n    raise EntityNotFoundException('Catalog item not found.')\npyvcloud.vcd.exceptions.EntityNotFoundException: Catalog item not found.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1589005498.875999-56849093850808/AnsiballZ_vcd_vapp_vm.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1589005498.875999-56849093850808/AnsiballZ_vcd_vapp_vm.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1589005498.875999-56849093850808/AnsiballZ_vcd_vapp_vm.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_vcd_vapp_vm_payload_lp3uvkx9/__main__.py\", line 584, in <module>\n  File \"/tmp/ansible_vcd_vapp_vm_payload_lp3uvkx9/__main__.py\", line 578, in main\n  File \"/tmp/ansible_vcd_vapp_vm_payload_lp3uvkx9/ansible_vcd_vapp_vm_payload.zip/ansible/module_utils/basic.py\", line 2067, in fail_json\n  File \"/tmp/ansible_vcd_vapp_vm_payload_lp3uvkx9/ansible_vcd_vapp_vm_payload.zip/ansible/module_utils/basic.py\", line 2039, in _return_formatted\n  File \"/tmp/ansible_vcd_vapp_vm_payload_lp3uvkx9/ansible_vcd_vapp_vm_payload.zip/ansible/module_utils/basic.py\", line 418, in remove_values\n  File \"/tmp/ansible_vcd_vapp_vm_payload_lp3uvkx9/ansible_vcd_vapp_vm_payload.zip/ansible/module_utils/basic.py\", line 401, in _remove_values_conditions\nTypeError: Value of unknown type: <class 'pyvcloud.vcd.exceptions.EntityNotFoundException'>, Catalog item not found.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
`

**Comment by inetman28** [comment]
Could you please provide example of your playbook? I use vCD 10.1 and these modules work.

**Comment by mukultaneja** [comment]
@anudeep404, the error says "Catalog item not found.". Could you please check if the catalog item present in VCD?

**Comment by mukultaneja** [comment]
@anudeep404, Please refer the [docs](https://github.com/vmware/ansible-module-vcloud-director/wiki) for module usage and feel free to reopen the issue if you need any help on this.
