### ISSUE TITLE
Ansible module vcloud director with Tower Inventory

### ISSUE THREAD

**Issue by Lupis619** [vmware/ansible-module-vcloud-director#117]
Will this module work for Ansible Tower?  How do i go about discovering the vCloud director in the inventory or in the Credentials?  Still sort of new to Tower so maybe I'm just over looking it but there seems to be little to no info on using this module with Tower.

**Comment by mukultaneja** [comment]
@Lupis619 I just look into this [demo](https://www.ansible.com/products/tower/setup) and I am sure you already have looked into it.
I guess inventory and credentials are ansible concepts and mostly machine-specific details. I suppose you would not need to do much stuff to discover vCloud director just specify details such as ip/user/password mention in your client like [here](https://github.com/vmware/ansible-module-vcloud-director/blob/master/main.yml)

**Comment by Lupis619** [comment]
@mukultaneja Yes, I have.  I have setup it up the way I "think" it should but receive "The error was: ModuleNotFoundError: No module named 'pyvcloud' " So I'm guessing I set something up wrong since it works perfectly fine with Ansible cli.  I'm still new to Ansible Tower so it could be something else that I've setup wrong but just kind of hit a wall since there is no info on using this module with Ansible tower.

**Comment by mukultaneja** [comment]
Just to confirm, have you installed pyvcloud? This is a python error and it generally comes when it did not find a module.

**Comment by Lupis619** [comment]
Yes I have it installed.  the playbook even works with Ansible cli.  just not Tower.  This is why I am confused.  Maybe I'm looking in the wrong place for the issue.

**Comment by planeturban** [comment]
@Lupis619 You probably need to add a venv with pyvcloud for Tower. 

https://docs.ansible.com/ansible-tower/latest/html/upgrade-migration-guide/virtualenv.html

**Comment by Lupis619** [comment]
@planeturban thank you.  I tried to create it, and think I did it right but selecting the Ansible Environment in the organization is missing.  I am using Anisble Tower V 3.7 with CentOS8.  Not sure what I'm missing.

**Comment by Lupis619** [comment]
I was able to figure out all of my problems.  The venv that was created was not activated correctly with the API commands. Also apparently you cannot use the username/password in credentials and host info in inventory in the Ansible Tower.  It has to be in the playbook.
