### ISSUE TITLE
**_AttributeError: 'NoneType' object has no attribute 'get' **fatal: [localhost]: FAILED! with host variable

### ISSUE THREAD

**Issue by carldubois** [vmware/ansible-module-vcloud-director#118]
Getting an attribute error with hosts in playbook.
Can someone explain this behavior?

Thanks,

- name: vCD-Ansible
  hosts: localhost
  environment:
    env_user: duboisc
    env_password: ###############
    env_host: vcloud.wwtatc.local
    env_org: vcd-sand
    env_api_version: 30.0
    env_verify_ssl_certs: false
  roles:
  #    - catalogs
  #    - user
      - vapp
#      - vappvm
#      - vdc
#      - disk
#      - org

#      - catalog_itemThe full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python3.8/runpy.py", line 206, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_vcd_vapp_payload_yvfq5tqy/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py", line 520, in <module>
  File "/tmp/ansible_vcd_vapp_payload_yvfq5tqy/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py", line 502, in main
  File "/tmp/ansible_vcd_vapp_payload_yvfq5tqy/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py", line 223, in __init__
**_AttributeError: 'NoneType' object has no attribute 'get'
**fatal: [localhost]: FAILED! => {
    "changed": false,**_**
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 102, in <module>\n  File \"<stdin>\", line 94, in _ansiballz_main\n  File \"<stdin>\", line 40, in invoke_module\n  File \"/usr/lib/python3.8/runpy.py\", line 206, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vcd_vapp_payload_yvfq5tqy/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py\", line 520, in <module>\n  File \"/tmp/ansible_vcd_vapp_payload_yvfq5tqy/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py\", line 502, in main\n  File \"/tmp/ansible_vcd_vapp_payload_yvfq5tqy/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py\", line 223, in __init__\nAttributeError: 'NoneType' object has no attribute 'get'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by mukultaneja** [comment]
@carldubois, I am maintaining a client `main.yml` which composed of Ansible Roles to consume these modules. The concept behind using `roles` in `main.yml` to separate out multiple plays such as create `catalog / vapp` to their own namespace and have a clean `main.yml` at last.
You can either use the existing `main.yml` and have respective roles with their own plays [for example](https://github.com/vmware/ansible-module-vcloud-director/blob/master/roles/catalogs/tasks/main.yml) or have your own way to consume these modules.
