### ISSUE TITLE
Guest customization not enabled

### ISSUE THREAD

**Issue by urajio** [vmware/ansible-module-vcloud-director#12]
"Enable Guest Customization" option disabled for new VM created from template.

**Comment by mukultaneja** [comment]
@urajio Thanks for reaching out! It would be helpful if you elaborate the use case more.

**Comment by pasikarkkainen** [comment]
Guest Customization is required to (re)configure the new provisioned VM settings, such as hostname, apply new network/IP settings, set root/admin password, and configure the guest customization script (which is important for setting up ssh authorized keys, etc).

So Guest Customization is absolutely a required feature for any automatic VM provisioning.

**Comment by urajio** [comment]
In our case it turned out that the reason is not in Ansible. Sorry, close this case.
