### ISSUE TITLE
connecting to Vcloud Director help

### ISSUE THREAD

**Issue by Gocmk** [vmware/ansible-module-vcloud-director#125]
We are using Vcloud dirtector (with resticted access)
I have created a powershell script that connects to our VCloud and creates a 
copy of a VM and then snapshots it.

We are starting to look at ansiable and I wish to do what I am doing with Powershell 
but in ansible.

THe powershell code I use to connect to our Vcloud is

$vcd02="https://vcd02.XXXXX.XXXX.XXX.xx"
$orgArp="s02_I_a02"

Connect-CIServer -Server "$vcd02 -org "$orgArp

The proper web address is like
https://vcd02.XXXXX.XXXX.XXX.xx/tenant/s02_i_a02/vdcs/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/vm

So I am looking at the below code for ansiable

---
- hosts: localhost
   
  tasks:
   - name: Include Secret Environment Items
     include_vars:
       file: secrets.yml
       name: secret
   
   - name: vCenter Login
     uri:
       url: "https://{{secret.vcenter}}" 
       force_basic_auth: yes
       method: POST
       user: "{{secret.username}}"
       password: "{{secret.password}}"
       status_code: 200
       validate_certs: no
      register: login

I need a proper hosts name. Just cant work it out
in the secrets.yml
I have the following
---
vcenter:  vcd02.XXXXX.XXXX.XXX.xx/tenant/s02_i_a02/vdcs
username: ##############
password: ###############

So when I use the following command
ansible-playbook dev-pb_Vcloud_connection.yml --extra-vars "hostlist=https://vcd02.XXXXX.XXXX.XXX.xx" --check

I get the following error

TASK [Gather all registered virtual machines] ***********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Hostname parameter is missing. Please specify this parameter in task or export environment variable like 'export VMWARE_HOST=ESXI_HOSTNAME'"}

Can some one give me a hand ?

**Comment by mukultaneja** [comment]
Hi @Gocmk, these modules are specifically for vCloud Director. You don't need to login to vCenter but to vCloud Director.  Please refer to the modules wiki [here](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-Ansible-Modules) and to create a VM snapshot [here](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-VM-Snapshot)
