### ISSUE TITLE
Migrate modules to Ansible Collection

### ISSUE THREAD

**Issue by Akasurde** [vmware/ansible-module-vcloud-director#129]
Hi Team,

Ansible now supports [collections](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html). It would be great if we can move this code to collection compatible structure and publish it using galaxy.ansible.com.

Let me know if you need my help in converting this repo to collection.

**Comment by mukultaneja** [comment]
@Akasurde thanks for the suggestion. We can look forward to it in the near future.

**Comment by RobVerduijn** [comment]
we now have to jump through hoops to use the roles/modules in our tower environment,
a collection would make this a lot easier.

**Comment by Akasurde** [comment]
@mukultaneja Please let me know if you want me to open a PR to make required changes.

**Comment by mukultaneja** [comment]
@Akasurde, Please go ahead.

**Comment by Akasurde** [comment]
Requested namespace for vmware.vmware_cloud_director - https://github.com/ansible/galaxy/issues/2604

**Comment by Akasurde** [comment]
@mukultaneja Once namespace is issued, will start refactoring code here.

**Comment by mukultaneja** [comment]
@here, closing this issue as we have merged the required code into the collection branch.
