### ISSUE TITLE
VCD user creation error 

### ISSUE THREAD

**Issue by nsheraga** [vmware/ansible-module-vcloud-director#130]
i am gettig below error, even i am providing right password:

TASK [vcd : VCD USER creation] **************************************************************************************************************************************************************************************************************
task path: /data01/ansible/playbooks/roles/vcd/tasks/main.yml:1
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1595532828.72-16298-259117612317650 && echo ansible-tmp-1595532828.72-16298-259117612317650="` echo /root/.ansible/tmp/ansible-tmp-1595532828.72-16298-259117612317650 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vcd_user.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-16218pbjHfY/tmpD2kGzF TO /root/.ansible/tmp/ansible-tmp-1595532828.72-16298-259117612317650/AnsiballZ_vcd_user.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1595532828.72-16298-259117612317650/ /root/.ansible/tmp/ansible-tmp-1595532828.72-16298-259117612317650/AnsiballZ_vcd_user.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.6 /root/.ansible/tmp/ansible-tmp-1595532828.72-16298-259117612317650/AnsiballZ_vcd_user.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1595532828.72-16298-259117612317650/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_vcd_user_payload_nm7l8qb6/ansible_vcd_user_payload.zip/ansible/module_utils/vcd.py", line 45, in login
  File "/usr/local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 986, in set_credentials
    raise VcdException('Login failed.')
pyvcloud.vcd.exceptions.VcdException: Login failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1595532828.72-16298-259117612317650/AnsiballZ_vcd_user.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1595532828.72-16298-259117612317650/AnsiballZ_vcd_user.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1595532828.72-16298-259117612317650/AnsiballZ_vcd_user.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.vmware.vcd_user', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_vcd_user_payload_nm7l8qb6/ansible_vcd_user_payload.zip/ansible/modules/cloud/vmware/vcd_user.py", line 311, in <module>
  File "/tmp/ansible_vcd_user_payload_nm7l8qb6/ansible_vcd_user_payload.zip/ansible/modules/cloud/vmware/vcd_user.py", line 290, in main
  File "/tmp/ansible_vcd_user_payload_nm7l8qb6/ansible_vcd_user_payload.zip/ansible/modules/cloud/vmware/vcd_user.py", line 195, in __init__
  File "/tmp/ansible_vcd_user_payload_nm7l8qb6/ansible_vcd_user_payload.zip/ansible/module_utils/vcd.py", line 31, in __init__
  File "/tmp/ansible_vcd_user_payload_nm7l8qb6/ansible_vcd_user_payload.zip/ansible/module_utils/vcd.py", line 49, in login
ansible.module_utils.vcd_errors.VCDLoginError: Login failed for user administrator to org nalab_org
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_vcd_user_payload_nm7l8qb6/ansible_vcd_user_payload.zip/ansible/module_utils/vcd.py\", line 45, in login\n  File \"/usr/local/lib/python3.6/site-packages/pyvcloud/vcd/client.py\", line 986, in set_credentials\n    raise VcdException('Login failed.')\npyvcloud.vcd.exceptions.VcdException: Login failed.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1595532828.72-16298-259117612317650/AnsiballZ_vcd_user.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1595532828.72-16298-259117612317650/AnsiballZ_vcd_user.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1595532828.72-16298-259117612317650/AnsiballZ_vcd_user.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.vmware.vcd_user', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vcd_user_payload_nm7l8qb6/ansible_vcd_user_payload.zip/ansible/modules/cloud/vmware/vcd_user.py\", line 311, in <module>\n  File \"/tmp/ansible_vcd_user_payload_nm7l8qb6/ansible_vcd_user_payload.zip/ansible/modules/cloud/vmware/vcd_user.py\", line 290, in main\n  File \"/tmp/ansible_vcd_user_payload_nm7l8qb6/ansible_vcd_user_payload.zip/ansible/modules/cloud/vmware/vcd_user.py\", line 195, in __init__\n  File \"/tmp/ansible_vcd_user_payload_nm7l8qb6/ansible_vcd_user_payload.zip/ansible/module_utils/vcd.py\", line 31, in __init__\n  File \"/tmp/ansible_vcd_user_payload_nm7l8qb6/ansible_vcd_user_payload.zip/ansible/module_utils/vcd.py\", line 49, in login\nansible.module_utils.vcd_errors.VCDLoginError: Login failed for user administrator to org nalab_org\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

My VAR file:

vcd_host: 10.10.10.19
vcd_username: administrator
vcd_password: XXXXXXX
vcd_org: nalab_org
vcd_api_version: 34
ansible_python_interpreter: '/usr/bin/python3.6'

Task file:

- name: VCD USER creation
  vcd_user:
    host: "{{ vcd_host }}"
    user: "{{ vcd_username }}"
    password: "{{ vcd_password }}"
    org: "{{ vcd_org }}"
    api_version: "{{ vcd_api_version }}"
    verify_ssl_certs: False
    username: "test"
    userpassword: "Svvs123!"
    role_name: "Organization Administrator"
    state: "present"
  register: output

**Comment by mukultaneja** [comment]
Hi @nsheraga, it is not able to login to VCD with the given credentials. Please share the VCD version you are trying to login.

**Comment by nsheraga** [comment]
Hi @mukultaneja VCD version 10.1, same password i used for org and provider both and it worked

**Comment by nsheraga** [comment]
any help ?

**Comment by nsheraga** [comment]
any help ?

**Comment by mukultaneja** [comment]
@nsheraga I am sorry to miss giving the reply. Which org do you want to create a user for?

**Comment by nsheraga** [comment]
my org is vcd_org: nalab_org, i want create this org

**Comment by mukultaneja** [comment]
@nsheraga ok! there is a mistake I could see in `vcd_user` wiki documentation. I will update the docs but as of now please use below 3 properties to add a new user in vcd.
```
host:  vcd_host
user: vcd admin username
password: vcd admin password 
org: vcd admin org such as "system"
username: new user name
userpassword: user password
org_name: org for which you want to create the new user, in your case it would be nalab_org
```

`org` and `user` both can be created while logging in `system` org.

**Comment by nsheraga** [comment]
@mukultaneja i got same error, plase find my var file and playbook .. did i miss something ?

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_vcd_user_payload_2udrwuj_/ansible_vcd_user_payload.zip/ansible/module_utils/vcd.py", line 45, in login
  File "/usr/local/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 986, in set_credentials
    raise VcdException('Login failed.')
pyvcloud.vcd.exceptions.VcdException: Login failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1596569166.58-30950-161547974466389/AnsiballZ_vcd_user.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1596569166.58-30950-161547974466389/AnsiballZ_vcd_user.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1596569166.58-30950-161547974466389/AnsiballZ_vcd_user.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.vmware.vcd_user', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_vcd_user_payload_2udrwuj_/ansible_vcd_user_payload.zip/ansible/modules/cloud/vmware/vcd_user.py", line 311, in <module>
  File "/tmp/ansible_vcd_user_payload_2udrwuj_/ansible_vcd_user_payload.zip/ansible/modules/cloud/vmware/vcd_user.py", line 290, in main
  File "/tmp/ansible_vcd_user_payload_2udrwuj_/ansible_vcd_user_payload.zip/ansible/modules/cloud/vmware/vcd_user.py", line 195, in __init__
  File "/tmp/ansible_vcd_user_payload_2udrwuj_/ansible_vcd_user_payload.zip/ansible/module_utils/vcd.py", line 31, in __init__
  File "/tmp/ansible_vcd_user_payload_2udrwuj_/ansible_vcd_user_payload.zip/ansible/module_utils/vcd.py", line 49, in login
ansible.module_utils.vcd_errors.VCDLoginError: Login failed for user administrator to org system
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_vcd_user_payload_2udrwuj_/ansible_vcd_user_payload.zip/ansible/module_utils/vcd.py\", line 45, in login\n  File \"/usr/local/lib/python3.6/site-packages/pyvcloud/vcd/client.py\", line 986, in set_credentials\n    raise VcdException('Login failed.')\npyvcloud.vcd.exceptions.VcdException: Login failed.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1596569166.58-30950-161547974466389/AnsiballZ_vcd_user.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1596569166.58-30950-161547974466389/AnsiballZ_vcd_user.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1596569166.58-30950-161547974466389/AnsiballZ_vcd_user.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.vmware.vcd_user', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vcd_user_payload_2udrwuj_/ansible_vcd_user_payload.zip/ansible/modules/cloud/vmware/vcd_user.py\", line 311, in <module>\n  File \"/tmp/ansible_vcd_user_payload_2udrwuj_/ansible_vcd_user_payload.zip/ansible/modules/cloud/vmware/vcd_user.py\", line 290, in main\n  File \"/tmp/ansible_vcd_user_payload_2udrwuj_/ansible_vcd_user_payload.zip/ansible/modules/cloud/vmware/vcd_user.py\", line 195, in __init__\n  File \"/tmp/ansible_vcd_user_payload_2udrwuj_/ansible_vcd_user_payload.zip/ansible/module_utils/vcd.py\", line 31, in __init__\n  File \"/tmp/ansible_vcd_user_payload_2udrwuj_/ansible_vcd_user_payload.zip/ansible/module_utils/vcd.py\", line 49, in login\nansible.module_utils.vcd_errors.VCDLoginError: Login failed for user administrator to org system\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1




var file:
vcd_host: 10.10.10.19
vcd_username: administrator
vcd_password: **************
org: system
vcd_api_version: 34
ansible_python_interpreter: '/usr/bin/python3.6'
org_name: nalab_org

playboook:


- name: VCD USER creation
  vcd_user:
    host: "{{ vcd_host }}"
    user: "{{ vcd_username }}"
    password: "{{ vcd_password }}"
    org: "{{ org }}"
    api_version: "{{ vcd_api_version }}"
    verify_ssl_certs: False
    org_name: "{{ org_name }}"
    username: "test"
    userpassword: "Svvs123!"
    role_name: "Organization Administrator"
    state: "present"
  register: output

**Comment by mukultaneja** [comment]
@nsheraga, you are not missing anything. Please confirm if you are able to login using `administrator` as a user name with `{{ vcd_password }}` to org `system` from the web interface of VCD.

**Comment by nsheraga** [comment]
i am not seeing system as org:

i have logged is tenant using below URL 


https://10.10.10.19/tenant/nalab_org/vdcs using same user name 

and i will login administrator using below link:

https://10.10.10.19/provider/

![image](https://user-images.githubusercontent.com/53913231/89337057-f5112480-d65f-11ea-8798-0e880ea3cecc.png)

**Comment by nsheraga** [comment]
![image](https://user-images.githubusercontent.com/53913231/89337255-46b9af00-d660-11ea-893b-c66036721e83.png)

**Comment by mukultaneja** [comment]
@nsheraga, Could you please try with `34.0` instead of `34` once? `34.0` is the actual `Pyvcloud API` version and they are expecting the same value format from the user.

**Comment by mukultaneja** [comment]
@nsheraga, when you try login into `/provider` then VCD assigns `system` as a by default org which won't be listed under `Organizations`.

**Comment by nsheraga** [comment]
your great!!!! its worked after using version 34.0. thank you so much fro your help.

**Comment by nsheraga** [comment]
[WARNING]: The value 34.0 (type float) in a string field was converted to '34.0' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
[WARNING]: The value 0 (type int) in a string field was converted to '0' (type string). If this does not look like what you expect, quote the entire value to ensure it does not change.
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "alert_email": "",
            "alert_email_prefix": "",
            "api_version": "34.0",
            "deployed_vm_quota": "0",
            "description": "",
            "email": "",
            "full_username": "",
            "host": "10.10.10.19",
            "im": "",
            "is_alert_enabled": false,
            "is_default_cached": false,
            "is_enabled": true,
            "is_external": false,
            "is_group_role": false,
            "org": "system",
            "org_name": "nalab_org",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "role_name": "Organization Administrator",
            "state": "present",
            "stored_vm_quota": "0",
            "telephone": "",
            "user": "administrator",
            "username": "test",
            "userpassword": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "verify_ssl_certs": false
        }
    },
    "msg": "User test has been created"
}
