### ISSUE TITLE
Setting vApp sharing mode?

### ISSUE THREAD

**Issue by robleady** [vmware/ansible-module-vcloud-director#133]
By default it appears that vApps created using vcd_vapp are private to the user that creates them.

I can use the vCloud Director GUI to modify the vApp after creation so that it's shared with everyone in the organisation, but I can't see any way of setting the sharing mode using the ansible modules.

Is it possible?

**Comment by mukultaneja** [comment]
Hey @robleady, sure it is possible. Let me add this for you in the module. Stay tuned 👍

**Comment by mukultaneja** [comment]
@robleady I have added a patch to provide operations to share/unshare a vApp across org. I have also added this operation in [wiki](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp). Please try it out.

**Comment by robleady** [comment]
Thanks for the quick response @mukultaneja 
I've done a couple of quick tests and it appears to be working as expected :-)
