### ISSUE TITLE
vcd_vapp_vm_nic, not updating NIC

### ISSUE THREAD

**Issue by danielc256** [vmware/ansible-module-vcloud-director#138]
Hello, I have 2 situations

1.
when I try to update my first NIC (created using the parameter network with vcd_vapp_vm module) I got the following message:

![image](https://user-images.githubusercontent.com/67828229/93714543-4f583d00-fb5b-11ea-9a95-ae5576243c33.png)

Note: Sorry for the image's quality, I'm in a datacenter with very limited access.

My playbook used:
![image](https://user-images.githubusercontent.com/67828229/93714573-8a5a7080-fb5b-11ea-8caa-f083328e1e4a.png)

2.
When I create a NIC instead of update I don't get this error, so if I could remove the parameter network on vcd_vapp_vm all would be okay (Theorically), but when I remove I receive another message:

![image](https://user-images.githubusercontent.com/67828229/93714652-271d0e00-fb5c-11ea-8ff1-379a2d70839a.png)

Note: I just removed the parameter network in vcd_vapp_vm module, so that I could create the NIC on the proper module, so why is it trying to search this network "NAT" and stopping the script?

Even though the machine is created, but it stops the playbook after this message, see on GUI the same output:

![image](https://user-images.githubusercontent.com/67828229/93714737-9692fd80-fb5c-11ea-9cc1-17c0a40e67bb.png)

I'm using Python 3.6.8 and pyvcloud 22.0.1 on RHEL8
My target is vCloud 9.7, API 32.0

**Comment by mukultaneja** [comment]
@danielc256, Please try to install a dev version of Pyvcloud using pip install pyvcloud==22.0.2.dev32 and let me know if it works well.

**Comment by mukultaneja** [comment]
@danielc256 are you able to resolve the issue?

**Comment by danielc256** [comment]
Yes, actually I was making a mistage.

If anyone have the error above, you must remove the network adapter of your template and create a new VM based on it.

In my case, it returns "Network NAT does not exist", it happens because my template was created out of vCloud and imported to it, maybe because of that the conflit.
