### ISSUE TITLE
need help adding second vapp network

### ISSUE THREAD

**Issue by sgutermann** [vmware/ansible-module-vcloud-director#143]
With vcd_vapp I can define the initial VDC Network I want to attach to the Vapp.

How do I add a second (third) existing VDC Network to the Vapp.

I used to be able to this with vcd_vapp_network. Now this is no longer working. I tried to adjust my playbook to the new parameters but reading and reading the documentation again it seems like all is now geared in terms of creating and changeing a Vapp Network. 

No obvious funktion to add an existing VDC Network to a Vapp.

**Comment by mukultaneja** [comment]
@sgutermann, do you want to attach an org VDC network to a VAPP?

**Comment by sgutermann** [comment]
@mukultaneja yes. With the unchanged modules in September this was easy. Just add another. With the update I can not add multiple VDC Networks at once or manage to add an extra one after creation.

**Comment by sgutermann** [comment]
@mukultaneja looks like the ame problem as mentioned in issue 136.

**Comment by sgutermann** [comment]
@mukultaneja, please see other thread. Adding the VDC Network to the vAPP now works. Getting it attached to the VM inside does not work.

**Comment by mukultaneja** [comment]
@sgutermann please close this issue if it is resolved

**Comment by sgutermann** [comment]
@mukultaneja closing this issue, getting it totally resolved is still not the case. Please see Issue 136.
