### ISSUE TITLE
How to update VDC memory, CPU and storage?

### ISSUE THREAD

**Issue by surfer190** [vmware/ansible-module-vcloud-director#145]
Is there a way to update the VDC resources using this module?

I tested the `vcd_org_vdc` task with `state: "update"` and it seems you can only update the status.
I tried to use the `state: "create"` and it says `[WARNING]:  VDC xxxx is already present.`

**Comment by mukultaneja** [comment]
@surfer190, a [new ](https://github.com/vmware/pyvcloud/pull/727)pull request to Pyvcloud is on the way. Stay tuned!

**Comment by surfer190** [comment]
Excellent, thanks @mukultaneja

**Comment by mukultaneja** [comment]
Just to keep track, please allow me to reopen the issue for a few days.
