### ISSUE TITLE
vcd_gateway_services

### ISSUE THREAD

**Issue by kokkerhout** [vmware/ansible-module-vcloud-director#147]
Hi,

I am missing the possibility to fully configure the Edge Gateway. The only thing I can configure is 'Firewall'
I'm also looking for the option to configure everyhting else. Like NAT, Routing, VPN, Certificates and so on.

Is this included in the modules? Or is it on a roadmap?

Thanks

**Comment by mukultaneja** [comment]
@kokkerhout, thanks for using the new module. The work is going on for all the other configurations. Stay tuned!

**Comment by kokkerhout** [comment]
Very cool. I appreciate. Can you give a expected time of arrival? Globally of course. Thanks a lot

**Comment by mukultaneja** [comment]
@kokkerhout, I have added a patch to create/update/delete a list of firewall rules through a single ansible play. Please try it once.
