### ISSUE TITLE
Enhancement: Edge Gateway Services create/update/delete at once

### ISSUE THREAD

**Issue by ntelisil** [vmware/ansible-module-vcloud-director#150]
It would be great if the _vcd_gateway_services_ module could support a **list** of rules to be created, updated or deleted instead of only a single one.
A _delete_all_ 'state' would also be very useful.

With respect to IaaC, nowdays the rules (e.g. firewall, NAT, ...) are saved in scm in a suitable format like yaml.
The idea is to pass the set of rules as a whole to the module instead of one rule at a time.
The module will compare the provided rules with the rules already present and will create, update or delete accordingly.

Benefits:

- Simplicity
The user will only have to provide the a list of rules and the module will take care the rest.
Right now, it is user's responsibility to traverse the existing rules, compare them with the new ones and make the appropriate requests - create new, update existing or delete for each difference.
- Speed
The number of requests will be greatly reduced as the rules will be grouped and send as payload with a single request (or 2-3 of them depending on the changes) instead of sending a request for each one rule.

Looking also forward to the support of NAT rules ++ as described in issue https://github.com/vmware/ansible-module-vcloud-director/issues/147/.

**Comment by mukultaneja** [comment]
@ntelisil, thanks for elaborating on the issue nicely. I am on it, things are in progress. Stay tuned!
