### ISSUE TITLE
force_recustomization not in wiki

### ISSUE THREAD

**Issue by 387119** [vmware/ansible-module-vcloud-director#152]
there is no parameter for force recustomization in wiki https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-VM
meantime there is parameter in python file itself
[~/ansible-module-vcloud-director/modules]$ sed -n 152,157p vcd_vapp_vm.py                                                     ✔[master]
    force_customization:
        description:
            - whether or not to force customization
        required: false
author:
    - mtaneja@vmware.com

is it missed or its going to be disabled/moved ?

**Comment by mukultaneja** [comment]
@387119 nice catch, thanks for reporting! I just updated the [wiki](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-VM#deploy-vapp-vm) page with the parameter. `force_customization` primarily goes with the `deploy_vm` operation.
