### ISSUE TITLE
Describe how to install the module

### ISSUE THREAD

**Issue by kgawda** [vmware/ansible-module-vcloud-director#162]
Is there a way to install the module into local Ansible setup? I tried copying the module directory into `~/.ansible/plugins/modules/`, but it didn't work. Currently I just clone the repository and work within this clone, but that seems good only for module development, not for creating and running actual playbooks.
Please describe the installation method in README.

**Comment by mukultaneja** [comment]
@kgawda you can mention the modules path in `ansible.cfg` as we already have as part of this repository. In this way, you can write playbooks at a different locations and refer to these modules to be used.

**Comment by mukultaneja** [comment]
@kgawda did this solution work for you?

**Comment by kgawda** [comment]
@mukultaneja yes, I think it is a good workaround: I did clone the repository to arbitrary catalog, and then reference it in `ansible.cfg` in other directory where I develop a playbook. And this works.

As a goal solution, is it possible to make the module work with instructions from [Ansible docs](https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html)? Like this one: 
> To load your local modules automatically and make them available to all playbooks and roles, add them in any of these locations:
>
>* any directory added to the ``ANSIBLE_LIBRARY`` environment variable (``$ANSIBLE_LIBRARY`` takes a colon-separated list like ``$PATH``)
>* ``~/.ansible/plugins/modules/``
>* ``/usr/share/ansible/plugins/modules/``

This does not work. When I clone the repo into `~/.ansible/plugins/modules/` and try to use it (eg. `ansible localhost -m vcd_vapp`) in other directory, I get: *"Could not find imported module support code for vcd_vapp.  Looked for either VcdAnsibleModule.py or vcd.py"*

**Comment by mukultaneja** [comment]
I think instead of cloning the repo inside `~/.ansible/plugins/modules/` try to copy all the individual module files there which you want to use.
