### ISSUE TITLE
Disk name in vcd_vapp_vm_disk can not be set

### ISSUE THREAD

**Issue by sgutermann** [vmware/ansible-module-vcloud-director#17]
The vcd_vapp_vm_disk module does use the disk_name parameter in the code but does not allow it to be set by the user through ansible.

With having multiple disks on a machine it gets a bit confusing when they are all called harddrive 0 harddrive 1 harddrive 2 etc.

**Comment by sgutermann** [comment]
Second thoughts on this: Would be nice to get that working with the name. So if at a later time I have to expand the drive I can just talk to that disk by name.

Currently this is only possible by disk_id which I don't see or get back anywhere currently.

**Comment by mukultaneja** [comment]
@sgutermann, as I have seen the disk name is always constant from VCD side itself which means it will always be in the form of Hard Disk {COUNT_OF_TOTAL_DISK}.

**Comment by mukultaneja** [comment]
@sgutermann, I have tried to add some workaround. Please take a look at below commit and let me know if it is useful.
https://github.com/vmware/ansible-module-vcloud-director/commit/2b8473fe30bf5f96fa6e15ceab0eb9a6edba1a7d

**Comment by sgutermann** [comment]
@mukundaramanna thank you for checking. I looked at the code. Ok, so if the name can not be set by me I can live with that. The main Problem I was trying to resolve was that I had no clue on how to get the disk id read out via the module. Meaning if I want to expand the size of a particular disk later in time I had no way of knowing (other than reading the machine data via curl and the API directly) which disk id I need.

Further on, after discovering the disk id (in my case 2000 and 2001) I was not able to use this to expand the disk.

Ok, so I will have to have antoher look at this, as I was hoping if I was albe to set the disk name I could use this to identify the disk later in time,.

**Comment by mukundaramanna** [comment]
@sgutermann I suppose your comment was meant for @mukultaneja
