### ISSUE TITLE
vcd_vapp_vm_nic Update on non-primary nic

### ISSUE THREAD

**Issue by CollabSensei** [vmware/ansible-module-vcloud-director#170]
The "nic_ids" parameter is ignored on nic updates. Therefore anytime an update is performed it occurs on the first nic.

          - name: Enable NIC
            vcd_vapp_vm_nic:
                    user:  "{{ env_user }}"
                    vapp: csr14b
                    password: "{{ env_password }}"
                    org: vOrg"
                    host: "{{ env_host }}"
                    vdc: "vDC"
                    vm_name: DESKTOP01
                    network: myNet
                    is_connected: True
                    state: update
                    nic_ids:
                     - 2

**Comment by mukultaneja** [comment]
@CollabSensei, Sorry for the delay in response, and thanks for raising an issue. I just updated the module. Please follow the latest [wiki](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-VM-Nic) to add/update/delete multiple NICs of a VM at a time. Try it out the latest patch and feel free to reopen the issue if things don't work for you.

**Comment by DanielFarrarCO** [comment]
Getting an error with the new format when doing a nic update.  The state "present" works when creating the nic but not state "update".

    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_vcd_vapp_vm_nic_payload_kn2t_i1p/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py\", line 307, in main\n  File \"/tmp/ansible_vcd_vapp_vm_nic_payload_kn2t_i1p/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py\", line 163, in manage_states\n  File \"/tmp/ansible_vcd_vapp_vm_nic_payload_kn2t_i1p/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py\", line 249, in update_nic\nTypeError: update_nic() got an unexpected keyword argument 'nic_id'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/tmp/.ansible-/ansible-tmp-1619633947.5339828-138254128423779/AnsiballZ_vcd_vapp_vm_nic.py\", line 247, in <module>\n    _ansiballz_main()\n  File \"/tmp/.ansible-/ansible-tmp-1619633947.5339828-138254128423779/AnsiballZ_vcd_vapp_vm_nic.py\", line 237, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/.ansible-/ansible-tmp-1619633947.5339828-138254128423779/AnsiballZ_vcd_vapp_vm_nic.py\", line 108, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.vcd_vapp_vm_nic', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_vcd_vapp_vm_nic_payload_kn2t_i1p/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py\", line 321, in <module>\n  File \"/tmp/ansible_vcd_vapp_vm_nic_payload_kn2t_i1p/ansible_vcd_vapp_vm_nic_payload.zip/ansible/modules/vcd_vapp_vm_nic.py\", line 315, in main\n  File \"/tmp/ansible_vcd_vapp_vm_nic_payload_kn2t_i1p/ansible_vcd_vapp_vm_nic_payload.zip/ansible/module_utils/basic.py\", line 2093, in fail_json\n  File \"/tmp/ansible_vcd_vapp_vm_nic_payload_kn2t_i1p/ansible_vcd_vapp_vm_nic_payload.zip/ansible/module_utils/basic.py\", line 2065, in _return_formatted\n  File \"/tmp/ansible_vcd_vapp_vm_nic_payload_kn2t_i1p/ansible_vcd_vapp_vm_nic_payload.zip/ansible/module_utils/basic.py\", line 418, in remove_values\n  File \"/tmp/ansible_vcd_vapp_vm_nic_payload_kn2t_i1p/ansible_vcd_vapp_vm_nic_payload.zip/ansible/module_utils/basic.py\", line 401, in _remove_values_conditions\nTypeError: Value of unknown type: <class 'TypeError'>, update_nic() got an unexpected keyword argument 'nic_id'\n",

Also, it appears that the "add_nic_task" does not reference "nic_id" but "update_nic_task" does.  In fact, that may be the issue as I used "nic_id: 1" but looking at VCD the Nic ID is 0.  Trying to use "nic_id: 0"... No doesn't work when I use nic_id: 0 either.  Here's the 2 modules I'm using, 1st works 2nd doesn't:

- name: Create MANUAL NIC (works)
  vcd_vapp_vm_nic:
    vm_name: "{{ vm_name }}"
    vapp: "{{ vapp_name }}"
    vdc: "{{ vdc_name }}"
    state: "present"
    nics:
    - nic_id: 1
      network: "{{ vdc_network_name }}"
      ip_allocation_mode: MANUAL
      ip_address: "{{vm_ipaddress}}"
      is_connected: True
      adapter_type: VMXNET3
  when: vm_create.changed
  register: create_nic
  until: create_nic is not failed
  retries: 5
  delay: 10

- name: Update MANUAL NIC to DHCP (broken, update_nic() got an unexpected keyword argument 'nic_id')
  vcd_vapp_vm_nic:
    vm_name: "{{ vm_name }}"
    vapp: "{{ vapp_name }}"
    vdc: "{{ vdc_name }}"
    state: "update"
    nics:
    - nic_id: 1
      network: "{{ vdc_network_name }}"
      ip_allocation_mode: DHCP
      is_connected: True
  when: vm_create.changed
  register: dhcp_nic
  until: dhcp_nic is not failed
  retries: 5
  delay: 10

**Comment by mukultaneja** [comment]
@DanielFarrarCO, I think you are using an older version of pyvcloud. Could you please try with the updated version once?
