### ISSUE TITLE
vcd_org_vdc - use existing storage profile of *(Any)

### ISSUE THREAD

**Issue by hoggy77** [vmware/ansible-module-vcloud-director#173]
When we manually create an OrgVDC we can select the storage policy of *(Any), but using the ansible script I can't put that in or leave it blank.  I get the following error:  (I've replaced confidential data with the {{name}})

The full traceback is:
  File "/tmp/ansible_vcd_org_vdc_payload_0p3c7hc9/__main__.py", line 611, in main
    response = module.manage_states()
  File "/tmp/ansible_vcd_org_vdc_payload_0p3c7hc9/__main__.py", line 303, in manage_states
    return self.create()
  File "/tmp/ansible_vcd_org_vdc_payload_0p3c7hc9/__main__.py", line 396, in create
    is_enabled=is_enabled)
  File "/home/{{name}}/.virtualenvs/ansible/lib64/python3.6/site-packages/pyvcloud/vcd/org.py", line 1592, in create_org_vdc
    params)
  File "/home/{{name}}/.virtualenvs/ansible/lib64/python3.6/site-packages/pyvcloud/vcd/client.py", line 1444, in post_linked_resource
    media_type, extra_headers=extra_headers)
  File "/home/{{name}}/.virtualenvs/ansible/lib64/python3.6/site-packages/pyvcloud/vcd/client.py", line 1427, in post_resource
    extra_headers=extra_headers)
  File "/home/{{name}}/.virtualenvs/ansible/lib64/python3.6/site-packages/pyvcloud/vcd/client.py", line 1174, in _do_request
    _objectify_response(response, objectify_results))
  File "/home/{{name}}/.virtualenvs/ansible/lib64/python3.6/site-packages/pyvcloud/vcd/client.py", line 1179, in _response_code_to_exception
    raise BadRequestException(sc, request_id, objectify_response)

failed: [localhost] (item={'vcname': '{{name}}', 'name': '{{name}}', 'network_cidr': '{{name}}', 'gateway': '{{name}}', 'dns': '8.8.8.8', 'vmcount': '16', 'newname': '{{name}}', 'provider_vdc': '{{name}}', 'org_vdc': '{{name}}', 'fullname': '{{name}}', 'org': '{{name}}'}) => {
    "ansible_loop_var": "network",
    "changed": false,
    "invocation": {
        "module_args": {
            "allocation_model": "AllocationVApp",
            "api_version": "30.0",
            "cpu_allocated": null,
            "cpu_limit": null,
            "cpu_units": null,
            "description": null,
            "host": "{{name}}",
            "is_enabled": true,
            "is_thin_provision": null,
            "mem_allocated": null,
            "mem_limit": null,
            "mem_units": null,
            "network_pool_name": null,
            "network_quota": null,
            "nic_quota": null,
            "operation": null,
            "org": "System",
            "over_commit_allowed": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "provider_vdc_name": "{{name}}",
            "resource_guaranteed_cpu": 0.0,
            "resource_guaranteed_memory": 0.0,
            "state": "present",
            "storage_profiles": [],
            "user": "**{{name}}**",
            "uses_fast_provisioning": true,
            "vcpu_in_mhz": null,
            "vdc_name": "{{name}}",
            "vdc_org_name": null,
            "verify_ssl_certs": false,
            "vm_discovery_enabled": null,
            "vm_quota": 16
        }
    },
    "msg": "Status code: 400/BAD_REQUEST, [ 02d79ef3-22e8-4d10-9858-c7ef9ecda9ae ] HTTP 400 Bad Request\n - cvc-complex-type.2.4.a: Invalid content was found starting with element 'ResourceGuaranteedMemory'. One of '{\"http://www.vmware.com/vcloud/v1.5\":VdcStorageProfile}' is expected. (request id: 02d79ef3-22e8-4d10-9858-c7ef9ecda9ae)",
    "network": {
        "dns": "8.8.8.8",
        "fullname": "{{name}}",
        "gateway": "{{name}}",
        "name": "{{name}}",
        "network_cidr": "{{name}}",
        "newname": "{{name}}",
        "org": "{{name}}",
        "org_vdc": "{{name}}",
        "provider_vdc": "{{name}}",
        "vcname": "{{name}}",
        "vmcount": "16"
    }
}

**Comment by mukultaneja** [comment]
@hoggy77, Please refer to the Org VDC [wiki](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-Org-VDC) once and let me know if you still face issues.

**Comment by mukultaneja** [comment]
@hoggy77, I assume your query got resolved. Hence closing the issue but feel to reopen it if you still face issues.
