### ISSUE TITLE
Request for “Register an NSX-T Manager instance” vCD ansible module

### ISSUE THREAD

**Issue by aashnaam** [vmware/ansible-module-vcloud-director#175]
Register an NSX-T Manager Instance -  The provisioned NSX-T Manager cluster will be added as an endpoint to a vCD server. It can be done by the GUI by https://docs.vmware.com/en/VMware-Cloud-Director/10.0/com.vmware.vcloud.spportal.doc/GUID-592938A5-E2BA-4912-B389-C6181D41A38F.html

**Comment by mukultaneja** [comment]
submitted a [PR](https://github.com/vmware/pyvcloud/pull/764) to pyvcloud.

**Comment by mukultaneja** [comment]
The PR is merged to pyvcloud. Hence closing the issue.
