### ISSUE TITLE
vcd_vapp_vm_disk - could not parse documentation

### ISSUE THREAD

**Issue by sgutermann** [vmware/ansible-module-vcloud-director#18]
ansible-doc -t module vcd_vapp_vm_disk
ERROR! module vcd_vapp_vm_disk missing documentation (or could not parse documentation): Incorrect value for 'Required', a boolean is needed.: [False]

**Comment by mukultaneja** [comment]
@sgutermann, thanks for raising an issue. I have added a patch. Please pull the latest code.

**Comment by sgutermann** [comment]
Great. works. Thank you.
