### ISSUE TITLE
Is there a way to disable the vcd_pysdk.log file?

### ISSUE THREAD

**Issue by ekoudijs** [vmware/ansible-module-vcloud-director#188]
In the repo i work in, i got a file vcd_pysdk.log with this kind of logging lines:
--
21-03-11 15:07:33 | client:947 - set_credentials | DEBUG :: API version in use: 32.0
21-03-11 15:26:30 | client:947 - set_credentials | DEBUG :: API version in use: 32.0
21-03-12 10:44:00 | client:947 - set_credentials | DEBUG :: API version in use: 32.0
21-03-12 15:40:36 | client:947 - set_credentials | DEBUG :: API version in use: 32.0
21-03-12 16:01:43 | client:947 - set_credentials | DEBUG :: API version in use: 32.0
21-03-23 10:57:40 | client:947 - set_credentials | DEBUG :: API version in use: 32.0
21-03-23 11:34:43 | client:947 - set_credentials | DEBUG :: API version in use: 32.0
21-03-23 15:47:20 | client:947 - set_credentials | DEBUG :: API version in use: 32.0
21-03-23 16:25:18 | client:947 - set_credentials | DEBUG :: API version in use: 32.0
21-03-23 16:28:33 | client:947 - set_credentials | DEBUG :: API version in use: 32.0
--

Is there a way to disable this logging file in the module?

**Comment by mukultaneja** [comment]
@ekoudijs, ansible modules do not generate `vcd_pysdk.log` but pyvcloud does. As of now, there is no provision to say no to log files in pyvcloud.

**Comment by ekoudijs** [comment]
I added the file to my .gitignore
