### ISSUE TITLE
Missing code from PR #161

### ISSUE THREAD

**Issue by kgawda** [vmware/ansible-module-vcloud-director#204]
### Describe the bug

Branch `master` is missing code changes from Pull Request #161.
When you see the PR details, it says it was accepted and merged by @mukultaneja into master. But this merge is not visible on commits list, and in code files.

This PR is adding two useful lines in `module_utils/gateway_nat_rule_service.py`.

### Reproduction steps

```bash
Compare:
 - https://github.com/vmware/ansible-module-vcloud-director/pull/161/files
 - https://github.com/vmware/ansible-module-vcloud-director/blob/master/module_utils/gateway_nat_rule_service.py#L48
```

### Expected behavior

Following lines should be present in `module_utils/gateway_nat_rule_service.py` in branch master:

```python
                if hasattr(nat_rule, 'description'):
                    nat_rule_info['Description'] = str(nat_rule.description)
```

**Comment by mukultaneja** [comment]
@kgawda I apologize for the inconvenience caused by the missing commit.  I have added the change through a new PR, hope it will resolve the issue.
