### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by whoamiUNIX** [vmware/ansible-module-vcloud-director#205]
### Describe the bug

I see in ansible documentation few stuff which will be deprecated. I also do not see frequent commit here and releases.

just want to know before I start using roles and modules which will be not updated.

### Reproduction steps

```bash
1.
2.
3.
...
```

### Expected behavior

.

**Comment by mukultaneja** [comment]
@whoamiUNIX, No it is not dead. Please use this project and raise issues if you have any.

**Comment by whoamiUNIX** [comment]
I see that community requesting some features. There are some older than 1year. To me it does not looks as active development. 
For example create standolone VM. There at least 2 issues releated to this and nothing was implemented…

**Comment by mukultaneja** [comment]
I am sorry for the delay. I got tied up in some other projects but now I am trying to put my focus back on this project as well.
