### ISSUE TITLE
Support for Edge configuration

### ISSUE THREAD

**Issue by carmineesposito73** [vmware/ansible-module-vcloud-director#26]
Hi, is anyone working on a module to configure edges?
IMHO, nat and fw configuration would be the most important features.
thanks

**Comment by sgutermann** [comment]
I would second that. Currently testing with one network, but as soon as testing is over some automation on that part would be nice.

**Comment by sgutermann** [comment]
The VPN SSL-Plus section would be nice as well. Adding users by Hand goes without words.

**Comment by sgutermann** [comment]
@mukultaneja do you have any data on this? Sorry if I am bothering you, but if you do not answer on the side of vm ware it looks to me no one else is going to.

**Comment by mukultaneja** [comment]
@sgutermann, sure I would like to look into this.

**Comment by MichalTaratuta** [comment]
@sgutermann @mukultaneja have a look at PR #35

**Comment by sgutermann** [comment]
@MichalTaratuta ... Thank You ... unfortunately I can not test this module. As I am just on the user end and do not have the necessary rights.

**Comment by carmineesposito73** [comment]
SSL VPN service is available on advanced ede (NSX), so you should look at "vCloud Director API for NSX Programming Guide" (vcloud 8.20, for example)
https://pubs.vmware.com/vcd-820/index.jsp?topic=%2Fcom.vmware.vcloud.api.nsx.doc_27_0%2FGUID-3FDFECA8-5D0B-4432-9AF3-A8BFA5C23F7F.html

here the link to the pdf (API version 27.0)
https://pubs.vmware.com/vcd-820/topic/com.vmware.ICbase/PDF/vcloud_nsx_api_guide_27_0.pdf
