### ISSUE TITLE
error using vcd module

### ISSUE THREAD

**Issue by chechuironman** [vmware/ansible-module-vcloud-director#28]
Im getting continuously this error:

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "  File \"/var/folders/qy/lh_mfrzs7_nc1jbtcpl5gh600000gn/T/ansible_A03i4Y/ansible_module_vcd_vapp.py\", line 1\nSyntaxError: Non-ASCII character '\\xc2' in file /var/folders/qy/lh_mfrzs7_nc1jbtcpl5gh600000gn/T/ansible_A03i4Y/ansible_module_vcd_vapp.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

any idea?

**Comment by mukultaneja** [comment]
@chechuironman, I think it is related to argument's value(s) which are passed to `vcd_vapp` module.

**Comment by sgutermann** [comment]
Yes, this is not a module or ansible problem but looks 99% like a python problem. Data being passed is not UTF8.

@mukultaneja ... I would close the issue but I am not allowed to.

**Comment by mukultaneja** [comment]
@sgutermann, cool!
@chechuironman would be helpful if you can provide more information to clarify the issue.

**Comment by Antres** [comment]
Hi, I've same problem, do you have resolved?

Thank you

**Comment by sgutermann** [comment]
> Hi, I've same problem, do you have resolved?
> 
> Thank you

You have a "SyntaxError: Non-ASCII character '\xc2' in file ". Then check the line. Check what you are passing? Does it need to go in quotes? Do you have non ascii characters defined in your dictionary, playbook? Anywhwere?
