### ISSUE TITLE
vcd_vapp_vm_disk showing change where there is none

### ISSUE THREAD

**Issue by sgutermann** [vmware/ansible-module-vcloud-director#29]
- name: VMWARE_CLOUDDIRECTOR_CREATE_VM | Create additional data drive vapp vm disk
      vcd_vapp_vm_disk:
        vm_name: "{{ vmname }}"
        vapp: "{{ vappname }}"
        vdc: "{{ vdc }}"
        size: "{{ cloud.disk.datadrive.size|int|default(0) }}"
        state: "present"
      
The size is defined and not changing.

Running the playbook over an over and over again shows a change each time. Nothing noticeable changes on the vm.

**Comment by sgutermann** [comment]
OMG ... sorry to say, there is a change. I have 10+ drives attached to my VM now !!

**Comment by mukultaneja** [comment]
@sgutermann I did not understand the issue.

**Comment by mukultaneja** [comment]
@sgutermann, Yes you are taking it wrong. Here 'present' equivalent to 'create' so every time when you run the module it will create a new disk.

**Comment by kaneda-fr** [comment]
Hi,
Shouldn’t the behavior be to create only if it has not been created in a previous run?

**Comment by sgutermann** [comment]
Yes, normal behavior for an ansible module is "present" = present and nothing else.

But I think this is similar to what I had a few weeks ago. The problem seems to be with the Disk Name. So I will try this with adding the Disk Name.

Simply means headsup for the disk name. As this is automagically created.

**Comment by mukultaneja** [comment]
@sgutermann as you are aware we can not set hard drive name while creating so I think there is no meaning to give hard drive name as an argument to the module while state being 'present'. So due to this limitation, the module will add a new disk and give you back the details of newly added details.

**Comment by sgutermann** [comment]
Yes.

Thank you for putting that straight again in my head.
