### ISSUE TITLE
vcd_vapp off of template without network not possible

### ISSUE THREAD

**Issue by sgutermann** [vmware/ansible-module-vcloud-director#30]
I am not sure where to start describing this or what logs to send.

It is reproducible but pretty time consuming to do so.

I created a vm by hand in vCloud. Then sysprept it. Powered it down. Removed in vCloud Director the Network and then templated it.

It is impossible to use this template with the vcd_vapp module, I have tried it all and asked the provider to check the logs. He can not make a rime of it either.

My temporary solution is to leave the network conntected when templating (pretty stupid but works).

THIS the module can handle. It will generate everything, add the right IP address and all.

Hower it now leaves the IP reserverd in vCloud for the Template and every machine templating off of the template needs to be in that network.

Ugly workaround.

Anyone else have a construct like that, or is this really only something in my universe?

**Comment by mukultaneja** [comment]
Hard Luck!!! Never face such type of scenarios. Would be helpful if you can share more details.

**Comment by sgutermann** [comment]
Sorry, I will try to explain it a bit more in detail.

When I use a regular Linux Template to create a vapp I can not reach it later on via ansible or ssh.

With a regular Linux Template I mean updated CentOs7 cleaned out (ssh keys, temp, history, udev, etc.).

If I leave the VM connected to the Network in VM Ware before templating. This is no issue. I can spin up any VM off of this template (of course only connected to the network which it was originally connected to.

But it looks like if you are the only one answering then I am the only one with such a strange issue and probably am missing something.

Ok.

Will have to do more testing in time to figure this one out.

**Comment by cmammoli** [comment]
I do it this way:
- create empty vapp linked to the org network I need (vcd_vapp)
- create a vm in the vapp linked with the org network and deploy=false (vcd_vapp_vm)
- set vm ip address if I need it to be static (vcd_vapp_vm_nic)
- power on the vm (vcd_vapp_vm)

**Comment by sgutermann** [comment]
@cmammoli there is currently no way that I can see to create this without the vapp if one does need it or not. Or am I mistaken here.

@mukultaneja looks like VM Ware has seen this the way I do, see my other Issue. As of two updates ago it is finally possible to create just a vm with the HTML5 Client, which means it should also be possible to do with the ansible modules.

@kaneda-fr how would I create a vm from template (your point three). I am not able to create a template from a vm in the first place. My Menu only let's me create a template from the whole vapp.

**Comment by sgutermann** [comment]
@mukultaneja this issue can be closed. This seemed to be a strange provider problem. They ran some updates and now this modules works as expected.
