### ISSUE TITLE
vcd_vapp_vm poweroff error when vm already powered off

### ISSUE THREAD

**Issue by sgutermann** [vmware/ansible-module-vcloud-director#31]
- name: VMWARE_CLOUDDIRECTOR_STOP_VM | Power off vm in vapp
      vcd_vapp_vm:
        target_vm_name: "test_vm"
        target_vapp: "test_vapp"
        target_vdc: "demo"
        operation: "poweroff"

Running this once does poweroff the VM nicely.

Running it a second time produces an ansible fail !!

Expected result: A simple message that the state is already powered off.

----------------------------------------------------------------------

TASK [VMWARE_CLOUDDIRECTOR_STOP_VM | Power off vm in vapp] ********************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: Value of unknown type: <class 'pyvcloud.vcd.exceptions.BadRequestException'>, Status code: 400/BAD_REQUEST, [ 7c292d2d-0255-4fdd-869e-09dbc38bb7f7 ] The requested operation could not be executed since VM "test_vm" is not powered on. (request id: 7c292d2d-0255-4fdd-869e-09dbc38bb7f7)
fatal: [test_vm -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):

File \"/tmp/ansible_vcd_vapp_vm_payload_kqrc3176/__main__.py\", line 568, in main

File \"/tmp/ansible_vcd_vapp_vm_payload_kqrc3176/__main__.py\", line 251, in manage_operations

File \"/tmp/ansible_vcd_vapp_vm_payload_kqrc3176/__main__.py\", line 466, in power_off_vm

File \"/home/foobar/.local/lib/python3.5/site-packages/pyvcloud/vcd/vm.py\", line 298, in power_off

operation_name='power off')

File \"/home/foobar/.local/lib/python3.5/site-packages/pyvcloud/vcd/vm.py\", line 249, in _perform_power_operation

vm_resource, rel, media_type, contents)

File \"/home/foobar/.local/lib/python3.5/site-packages/pyvcloud/vcd/client.py\", line 1088, in post_linked_resource

media_type)

File \"/home/foobar/.local/lib/python3.5/site-packages/pyvcloud/vcd/client.py\", line 1072, in post_resource

objectify_results=objectify_results)

File \"/home/foobar/.local/lib/python3.5/site-packages/pyvcloud/vcd/client.py\", line 861, in _do_request

response), _objectify_response(response, objectify_results))

File \"/home/foobar/.local/lib/python3.5/site-packages/pyvcloud/vcd/client.py\", line 866, in _response_code_to_exception

raise BadRequestException(sc, request_id, objectify_response)

pyvcloud.vcd.exceptions.BadRequestException: Status code: 400/BAD_REQUEST, [ 7c292d2d-0255-4fdd-869e-09dbc38bb7f7 ] The requested operation could not be executed since VM \"test_vm\" is not powered on. (request id: 7c292d2d-0255-4fdd-869e-09dbc38bb7f7)

**Comment by mukultaneja** [comment]
@sgutermann, I have added a patch to resolve this issue. Please check once the latest commit https://github.com/vmware/ansible-module-vcloud-director/commit/7ae26378ef11f931a2ba66569f41e7e5d3e2b57c

**Comment by sgutermann** [comment]
@mukultaneja 

No.

> The requested operation could not be executed since vApp \"workhorse01.opticadev.local\" does not have any powered on VMs.

Still produces a fail.

The other thing I noticed is that it actually does a poweroff on the VMs in the vApp, but only stops the vApp and does not power it off.

**Comment by mukultaneja** [comment]
@sgutermann Please confirm whether you are talking about vcd_vapp or vcd_vapp_vm module.

**Comment by sgutermann** [comment]
@mukultaneja sorry for answering this late, but I was a bit under water the last days.

I just checked again and believe it or not, my playbook is using the vcd_vapp module. As I am powering off the whole app.

I had originally started powering off the vom but switched to the whole app as I am only running one VM per APP.

Sorry for the confusion.

**Comment by mukultaneja** [comment]
@sgutermann As the issue says, the above patch is for `vcd_vapp_vm` module which checks the VM state before powering off/on the VM.

**Comment by mukultaneja** [comment]
@sgutermann, I have added the same check for vApps  https://github.com/vmware/ansible-module-vcloud-director/commit/126e7e55a8631b8fc8ccdaa0fdaecd11456edad1

**Comment by sgutermann** [comment]
@mukultaneja sorry for not answering sooner. Thank you. I updated everything on my machine and tried it and it now works as expected. :)
