### ISSUE TITLE
vcd_vapp_vm networking

### ISSUE THREAD

**Issue by AlexDyukov** [vmware/ansible-module-vcloud-director#32]
Hi there!

I have got an error in adding VM to exists VAPP. I have template without networks preset, so there is two ways:
1) setup VM w/o subnets
2) add subnet net1
3) add subnet net2
or
1) setup VM w/ subnet net1
2) add subnet net2

I'm having trouble with both of them:
in first case exception
AttributeError: no such child: {http://www.vmware.com/vcloud/v1.5}NetworkConnection
raised
in the second case exception
AttributeError: no such child: {http://www.vmware.com/vcloud/v1.5}PrimaryNetworkConnectionIndex
raised
I cannot add VM in any ways without presets in template.

settings:
https://gist.github.com/AlexDyukov/6123dc3a06d9264b077c5cb3323e7edf

if I'm doing it wrong, give a link to the docs, please.

**Comment by sgutermann** [comment]
Well I am not sure if I am any help. But you will find other issues regarding network problems.

Currently I have it only working by having my template already hooked up to the network. In other words I have a so called management net which is what I run ansible over. Every machine does have this network attached anyway.

I am currently working on getting other networks to attach as well but will be back onto that earliest in a few days.

So it is quite possible that you are per say no really doing anything wrong.

**Comment by carmineesposito73** [comment]
@AlexDyukov, does your vm has a nic in the template?
If so I can suggest a workaround:
* create the vm with no network configuration
* update network configuration using `vcd_vapp_vm_nic.py` module

**Comment by AlexDyukov** [comment]
@carmineesposito73 it doesnt matter which VM NIC in template, because create new VM going good anyway. `AttributeError: no such child:` raised in operation of NIC update, because its the same way as #1 of the topic

**Comment by carmineesposito73** [comment]
@AlexDyukov if I understand well you create the VM but you cannot configure the VM nics using  `vcd_vapp_vm_nic.py`, correct?

do you use the latest version of `vcd_vapp_vm_nic.py` (commited in january)?
actually I've found an issue (#34) but it works.

You can try also to read the vm nics to check is something is wrong
```
  tasks:
  - name: read vm nics
    vcd_vapp_vm_nic:
        vm_name: "{{ my_vm }}"
        vapp: "{{ my_vapp }}"
        vdc: "{{ my_vdc }}"
        operation: "read"
```
Here https://github.com/carmineesposito73/ansible-module-vcloud-director/blob/master/modules/vcd_vapp_vm_nic.py you can find my version of the module, this solves the issue above and has some enhancements

**Comment by mukultaneja** [comment]
@AlexDyukov Please try with updated vcd_vapp_vm_nic module. It has the capability to add/delete/update nics with given network details. Feel free to open the issue again in case of not working.
