### ISSUE TITLE
Roles partialy implemented 

### ISSUE THREAD

**Issue by TomaszBelina** [vmware/ansible-module-vcloud-director#33]
There are multiple issues in roles implementation.

1.  Hardcoded values, eg. Terraform_VDC in https://github.com/vmware/ansible-module-vcloud-director/blob/master/roles/vapp/tasks/main.yml
2. Questionable flow. For example what is the point of creating and destroying vApp in the same role like in  https://github.com/vmware/ansible-module-vcloud-director/blob/master/roles/vapp/tasks/main.yml ?

Generally speaking roles in the current implementation state shouldn't be merged into master. They are completely useless.

**Comment by sgutermann** [comment]
I agree that the "roles" are not really roles but rather samples. However omitting them completely does not make it easier in traying to understand this VM Ware construction of vApp vs VM.

**Comment by mukultaneja** [comment]
@TomaszBelina, "roles" are nothing but equal to test scripts to test these modules. I wrote these test scripts with internal (VMware) system values. Apart from testing, "roles" may help you to write your own playbooks as well.

**Comment by TomaszBelina** [comment]
Role is well defined concept in Ansible. Using roles for testing purpose is basically misleading for project users.

**Comment by sgutermann** [comment]
@TomaszBelina sounds ok either way to me. Do a pull request, let us see what you have got.
