### ISSUE TITLE
vcd_vapp SyntaxError

### ISSUE THREAD

**Issue by gm12367** [vmware/ansible-module-vcloud-director#38]
Dear Author

When I am trying to use vcd_vapp module, I'm facing below error. I completed followed guide and read me to setup my environment. Would you please to check this:

```
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1547550025.88-20448556516779/AnsiballZ_vcd_vapp.py", line 113, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1547550025.88-20448556516779/AnsiballZ_vcd_vapp.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1547550025.88-20448556516779/AnsiballZ_vcd_vapp.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_vcd_vapp_payload__5McFr/__main__.py", line 1
SyntaxError: Non-ASCII character '\xc2' in file /tmp/ansible_vcd_vapp_payload__5McFr/__main__.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1547550025.88-20448556516779/AnsiballZ_vcd_vapp.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1547550025.88-20448556516779/AnsiballZ_vcd_vapp.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1547550025.88-20448556516779/AnsiballZ_vcd_vapp.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_vcd_vapp_payload__5McFr/__main__.py\", line 1\nSyntaxError: Non-ASCII character '\\xc2' in file /tmp/ansible_vcd_vapp_payload__5McFr/__main__.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

run.yml:
```
---
- name: vCloudDirectorAnsible
  hosts: localhost
  environment:
    env_user: user-XXX
    env_password: password-XXX
    env_host: example.com
    env_org: example.org
    env_api_version: 30.0
    env_verify_ssl_certs: false

- name: create vapp
  hosts: localhost
  tasks:
    - vcd_vapp:
        vapp_name: "test_vapp_ansible"
        vdc: "example-vdc"
        state: "present"
      register: output
    - debug:
        msg: '{{ output }}'
```

Thanks!

**Comment by gm12367** [comment]
I even add "LC_ALL=en_US.utf8" into /etc/environment and "#coding=utf-8" in the head of modules/vcd_vapp.py, but neither help.

command "locale" output:
`LANG=en_US.UTF-8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=en_US.utf8
`

**Comment by sgutermann** [comment]
ansible --version

**Comment by gm12367** [comment]
Here is the ansible version output:

ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansre/ansible/plugins/modules']
  ansible python module location = /usr/lib/pyt
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018,ed Hat 4.8.5-36)]

**Comment by gm12367** [comment]
Below is the output, hope it can help.

ansible 2.7.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

**Comment by sgutermann** [comment]
**python version = 2.7.5** 

if I am not mistaken you need to be running ansible 2.7 and up with python3

**Comment by mukultaneja** [comment]
@gm12367 Please use python version 3 to use these modules.

**Comment by gm12367** [comment]
Thank you so much for your feedback, I can create Vapp successfully. And I tried vapp_vm module, it works as well.
