### ISSUE TITLE
vcd_vapp_vm_nic cannot change NetworkAdapterType

### ISSUE THREAD

**Issue by sgutermann** [vmware/ansible-module-vcloud-director#48]
I have a load of VMs that have a strange default adapter type assigned to them which is now causing problems in my environment.

Using VMXNET3 solves this.

However I can not find a way to change this on the machines.

**Comment by sgutermann** [comment]
Was this ever looked into or am I and this issue simply out of date?

**Comment by mukultaneja** [comment]
@sgutermann are you able to resolve this issue? I guess we already have this parameter in [place](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-VM-Nic)

**Comment by mukultaneja** [comment]
@sgutermann, I am closing this issue as of now. Please feel free to open it if you find any issues again.

**Comment by sgutermann** [comment]
Yes, sorry did not get around to testing till now. But yes adapter type seems to be usable.
