### ISSUE TITLE
Feature Request: snapshot managent with the vCloud provider

### ISSUE THREAD

**Issue by swerveshot** [vmware/ansible-module-vcloud-director#51]
### Environment
ansible-module-vcloud-director v1.0

### Proposed Functionality
As a service provider I would like to have the ability to offer tenants with the ability to control VM and/or vApp snapshots with the Ansible vCloud provider.

### Use Case
This feature would be benificial for tenants that want to be able to create snapshots automatically. For instance before executing an automated patch cycle on a selection of VMs / vApps.

**Comment by swerveshot** [comment]
It seems that pyvcloud only supports snapshots on a individual VM level. So it is currently not possible to have vApp snapshot support for Ansible provider.

**Comment by swerveshot** [comment]
Okay, so version [21.0.0 of pyvcloud](https://github.com/vmware/pyvcloud/releases/tag/21.0.0) has just shipped an it supposedly has a feature to create snapshots. As creating snapshots is only 1 part of the requested feature we'll have to wait a bit longer.

**Comment by mukultaneja** [comment]
Hello @swerveshot, Please give me some time to implement this feature request and if you have something to contribute feel free to do it.

**Comment by swerveshot** [comment]
Hi @mukultaneja, unfortunately my coding skills are near non-existent. Otherwise I'd be happy to prepare a pull request. So I'm afraid all I can contribute is testing whatever is developed by yourself or others.

**Comment by mukultaneja** [comment]
sure, no problem :)

**Comment by mukultaneja** [comment]
Hi @swerveshot, as requested I have added a new module to manage virtual machine snapshots through https://github.com/vmware/ansible-module-vcloud-director/commit/671edc4b6b4c8e1e4697a58324e21846e10d2fad. Please take a look and report any concerns you find.

**Comment by sgutermann** [comment]
@mukultaneja - thank you for your work. I had a breif look at your commit. The one thing I seem top be missing is "listing snapshots" or "getting details" on them.

I run over 100 VMs and funny enough there are only 10 of them I have snapshots from. 

Why?

Well those 10 are "snowflake" Servers. Meaning I did not set them up myself or they are Windows and have had some work done on them by hand.

So being able to list all VMs with snapshots would be tremendous help. Getting details on the snapshots as well. This way I do not have to klick through by hand looking for them and checking them, instead I run a playbook telling me all about it and then I can act accordingly, again with another playbook.

:)

As soon as this is ready for testing I am available.

;)

**Comment by sgutermann** [comment]
@mukultaneja sorry, finally got around to testing this. 

1. for starters it does do a snapshot
2. however the module does not honor the "--check"
3. when run again it simply does a new snapshot (not idemopotent)

So basic functionallity is present, thank you. Expected ansible behavior missing.

**Comment by Lupis619** [comment]
So is there a way to revert multiple snapshots at once?  Or just 1 VM at a time?  It also seems that it won't take the * character.  For example VM names "W2K16-1" "W2K16-2" etc, 'W2K16*" will not work at all.  Will this be added later on too?

**Comment by mukultaneja** [comment]
@sgutermann @Lupis619 Apologies for the late reply. I just added a patch to create/list multiple snapshots for VMs. Please try it out once.

**Comment by sgutermann** [comment]
@mukultaneja thank you. Listing seems to work now. @Lupis619 reverting or making multiple snapshots seems to be rather the playbook you wrote. Passing a group of names seems to work for me.

**Comment by mukultaneja** [comment]
@sgutermann @Lupis619 If you guys need any help with playbook writing, please refer to the sample playbook for the snapshot module [here](https://github.com/vmware/ansible-module-vcloud-director/blob/master/roles/vcd_vapp_vm_snapshot/tasks/main.yml). I keep these sample playbooks here so that user won't get hesitant and feel easy to use these modules. I am maintaining [wiki](https://github.com/vmware/ansible-module-vcloud-director/wiki/vCD-vApp-VM-Snapshot) for the modules as well. Feel free to raise your issues if you find any.

**Comment by sgutermann** [comment]
Thanks does for me what it was supposed to.
