### ISSUE TITLE
Problems with gateway configuration

### ISSUE THREAD

**Issue by mgaruccio** [vmware/ansible-module-vcloud-director#54]
I am attempting to use the recently added and edge gateway module and I'm running into trouble with a few items.  First, the module performs it's check for an existing gateway by using a `try/except` block but the `get_gateway` function it relies on returns `None` if a gateway isn't found.  This results in the module always reporting that the gateway exists, whether it does not not. 

I added an additional check to determine if there was a `None` response from the get_gateway function and encountered the error `fatal: [localhost]: FAILED! => {"changed": false, "msg": "'VDC' object has no attribute 'create_gateway'"}` after verifying that I am on pyvcloud 20.0.1 I dug into the  pyvcloud code and found that there is no `create_gateway()` function within `VDC` .  There are however 3 api version specific functions `create_gateway_api_version_30()`, `create_gateway_api_version_31()` and `create_gateway_api_version_32()`.  

Specifically modifying the module to use `create_gateway_api_version_31()` allowed the gateway to actually be created but get_gateway seems to return `None` regardless of whether a gateway with the specified name already exists, I'm guessing this is due to using a `System` user for the query rather than one that belongs to the tenant org but not sure how to work around that as tenant administrators cannot create edge gateways.

**Comment by mgaruccio** [comment]
Ok I figured out the issue.  The gateway module ONLY works if the pyvcloud version is 20.0.2, 20.0.1 doesn't have the gateway functions, 20.0.3 changes them to use the `_api_version` modifiers and 20.1.0 changes the way get_gateway works to return a `none` (seemingly regardless of whether there is a gateway there or not) instead of an exception.  

This feels more like issues with pyvcloud honestly but should probably be either handled by this module or at least noted in the docs.

**Comment by mukultaneja** [comment]
Hello @mgaruccio, thanks for raising this issue and apologies for this much late reply. I have added a new patch https://github.com/vmware/ansible-module-vcloud-director/commit/c0c49f0f25a6ad49e4bbecd12e0d074696084527 to simplify edge gateway module and incorporate all three methods provided by pyvcloud. Please take a look and let me know if any issues you find with latest module.
