### ISSUE TITLE
gateway_name should not be a vcd_vdc_network.py required argument

### ISSUE THREAD

**Issue by carmineesposito73** [vmware/ansible-module-vcloud-director#57]
since `vcd_vdc_network.py` is used to create also isolated and direct networks, `gateway_name` should not be a required argument

**Comment by mukultaneja** [comment]
@carmineesposito73, thanks for raising the issue. I have added a patch 570dd4d4a723925fa89352f71202bf19bfc8bf16 to resolve the issue. Please take a look!

**Comment by mukultaneja** [comment]
@carmineesposito73 Please allow me to close this issue and feel free to reopen it if you find any concerns.

**Comment by carmineesposito73** [comment]
it works, I've created an isolated network with no gateway_name as parameter

**Comment by mukultaneja** [comment]
thanks to update @carmineesposito73
