### ISSUE TITLE
VDC Resource limits

### ISSUE THREAD

**Issue by tfiedler** [vmware/ansible-module-vcloud-director#60]
Per the docs

```
cpu_allocated - (Optional) capacity that is committed to be available
```

I assume this means CPU Quota - does a 0 value mean unlimited or does it mean 0. If it means zero, how could I specify unlimited?

TY in advance
Ted

**Comment by mukultaneja** [comment]
It means unlimited because the minimum percentage value is never 0 but 0.26.

**Comment by mukultaneja** [comment]
@tfiedler please close this issue if your query is resolved.
