### ISSUE TITLE
Feature Request: create organization admin user when create org

### ISSUE THREAD

**Issue by okozarva** [vmware/ansible-module-vcloud-director#62]
Organization admin account cannot create when creating organization.

If you want to create an organization admin account for org, you can not create. Because you can not login to an organization with local admin user. So, we need to create organization admin user when creating organization.

Is it possible to add this feature?

**Comment by mukultaneja** [comment]
This feature is already available as part of the user module. To create a user for an organization, you have to pass the `org_name` as an argument with `role_name` as `admin` to the module.

**Comment by okozarva** [comment]
Hello,

Thank you for your reply.

I already tested this feature before creating this issue. This feature does not meet my requirements.

User module waits to login with organization admin account. Because you can not login to vcloud.com/org/test with local admin user. So, if there is no org admin account. You cannot login. I want to create first admin account under the organization.

I want to automate new customer provisioning on vcloud. So, I need to create organization admin account when creating organization.

**Comment by mukultaneja** [comment]
Hi,

Please try the following play to create an org and assign an admin user to it using the user module. Please confirm if you are giving "Organization Administrator" role to the new user.

    - name: create org
        vcd_org:
          org_name: Acme
          full_name: Acme
          is_enabled: true
          state: present
        register: output

      - name: create org output
        debug:
          msg: '{{ output }}'

      - name: create org user
        vcd_user:
          username: acmeadmin
          userpassword: ********
          org_name: Acme
          role_name: Organization Administrator
          full_username: acmeadmin
          description: Acme Admin
          is_enabled: true
          stored_vm_quota: 30
          deployed_vm_quota: 20
          is_default_cached: true
          state: present
        register: output

      - name: create user output
        debug:
          msg: '{{ output }}'

**Comment by okozarva** [comment]
It works. Thank you mukultaneja!
