### ISSUE TITLE
vcd_vapp_vm_nic is not idempotent

### ISSUE THREAD

**Issue by kaneda-fr** [vmware/ansible-module-vcloud-director#64]
Hi,

Each time running this module runs, it will create a new NIC for the network, even if one already exists.  The nic_id specified as parameter is not taken into account for the NIC creation.

An idempotent behavior would be to:
- when nic_id is NOT specified and the network is already connected to the VM - do nothing
- when a nic_id is specified and it already exist on that network - do nothing
- when a nic_id is specified and it already exist with a different network - update the network for that nic
- in all other case, create the network nic (using nic_id is specified)

Can you give me a feedback on the above and I can submit a module change.

**Comment by carmineesposito73** [comment]
I agree,
https://github.com/vmware/ansible-module-vcloud-director/issues/34#issuecomment-492248921

nic_id is not used in `vcd_vapp_vm_nic`, i've done my version here
https://github.com/carmineesposito73/ansible-module-vcloud-director/blob/master/modules/vcd_vapp_vm_nic.py

where nic_id is an optional parameter

**Comment by carmineesposito73** [comment]
anyway my version do not respect your bullet, your requirements are more complex.

herte my comment on them.

1. ok -> exception network already connected to that network
2. maybe can be useful to have more nics on the same network (if nic_id is not already used)
3. I prefer explicit `operation = update` to change nic network (to avoid unexpected modification)
4. in all other case, create the network nic (using nic_id if specified, or the first free nic_id if not specified)

my module do not respect bullet 1

**Comment by kaneda-fr** [comment]
Hi,

1. is quite key, otherwise each time you run the play, a new nic is added
2. ok with your proposal
3. i understand, it will be useful that the update can create / update. Otherwise, if you do not know the current state (not created or create with another network) you need to run 2 operations, or do a manual detection before doing a create or an update
4. ok

**Comment by wilmardo** [comment]
This issue over at Ansible might be related:
https://github.com/ansible/ansible/issues/38605

**Comment by mukultaneja** [comment]
@kaneda-fr @wilmardo @carmineesposito73 are we still seeing this issue?

**Comment by carmineesposito73** [comment]
@mukultaneja I do not use this module anymore

**Comment by wilmardo** [comment]
@mukultaneja Same here, I haven't used this module since last year.

This comment explains my findings at that point:
https://github.com/ansible/ansible/issues/38605#issuecomment-459739899

**Comment by kaneda-fr** [comment]
> @kaneda-fr @wilmardo @carmineesposito73 are we still seeing this issue?

I'm no longer working on this, so can't say.

**Comment by mukultaneja** [comment]
sure then let me close this issue but feel free to open it again if you need to.
