### ISSUE TITLE
VDC is already present

### ISSUE THREAD

**Issue by okozarva** [vmware/ansible-module-vcloud-director#66]
PLAY [vCloudDirectorAnsible] ***************************************************

TASK [create vdc] **************************************************************
 [WARNING]: VDC ansible_pool is already present.

ok: [localmachine]

TASK [create vdc output] *******************************************************
ok: [localmachine] => {
    "msg": {
        "changed": false,
        "failed": false,
        "warnings": [
            "VDC ansible_pool is already present."
        ]
    }
}

PLAY RECAP *********************************************************************
localmachine               : ok=2    changed=0    unreachable=0    failed=0

My task:

        - name: create vdc
          vcd_org_vdc:
               user: ansible_admin
               password: pass
               org: ansible
               vdc_name: "ansible_pool"
               provider_vdc_name: "Provider-VDC"
               description: "test vdc_ansible"
               allocation_model: "AllocationVApp"
               is_enabled: "true"
               storage_profiles:
               - name: "vCloud"
                 enabled: true
                 units: "MB"
                 limit: 50000
                 default: true
               cpu_units : "MHz"
               cpu_allocated : 2
               cpu_limit : 0
               mem_units : 'GB'
               mem_allocated : 4
               mem_limit : 0
               nic_quota : 0
               network_quota : 0
               vm_quota : 0
               resource_guaranteed_memory : 0
               resource_guaranteed_cpu : 0
               vcpu_in_mhz : 2000
               is_thin_provision : true
               uses_fast_provisioning : false
               over_commit_allowed : false
               state: "present"
          register: output

        - name: create vdc output
          debug:
            msg: '{{ output }}'

**Comment by okozarva** [comment]
All VDC names returned already present error.

**Comment by mukultaneja** [comment]
@okozarva Please try again with the latest code. You probably should not get this issue this time. I just have updated the `vdc_org` module code due to changes in `pyvcloud` library.

**Comment by okozarva** [comment]
It works. Thank you mukultaneja!
