### ISSUE TITLE
Unable to Run the playbooks

### ISSUE THREAD

**Issue by sureshpalemoni** [vmware/ansible-module-vcloud-director#72]
TASK [catalogs : create catalog] ****************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: Non-ASCII character '\xc2' in file /var/folders/nc/v4fymr5x12zfmm7mk49_rgjw0000gn/T/ansible_vcd_catalog_payload_XoqrUs/__main__.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/sp/.ansible/tmp/ansible-tmp-1560948808.22-96272297509022/AnsiballZ_vcd_catalog.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/Users/sp/.ansible/tmp/ansible-tmp-1560948808.22-96272297509022/AnsiballZ_vcd_catalog.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/Users/sp/.ansible/tmp/ansible-tmp-1560948808.22-96272297509022/AnsiballZ_vcd_catalog.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/var/folders/nc/v4fymr5x12zfmm7mk49_rgjw0000gn/T/ansible_vcd_catalog_payload_XoqrUs/__main__.py\", line 1\nSyntaxError: Non-ASCII character '\\xc2' in file /var/folders/nc/v4fymr5x12zfmm7mk49_rgjw0000gn/T/ansible_vcd_catalog_payload_XoqrUs/__main__.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by mgaruccio** [comment]
It looks like your running within Python2, take a look at [the ansible docs](https://docs.ansible.com/ansible/latest/reference_appendices/python_3_support.html) for info on running ansible using python3

**Comment by carmineesposito73** [comment]
to use python3 try this:

ansible hosts file (.ini format)
```
[vcloud]
localhost

[vcloud:vars]
ansible_python_interpreter=/usr/bin/python3
```

ansible hosts file (.yml format)
```
all:
  children:
    vcloud:
      hosts:
        localhost:   # it's a "dummy" host
      vars:
        ansible_python_interpreter: /usr/bin/python3
```

**Comment by sgutermann** [comment]
@sureshpalemoni can we see your "ansible --version" ?? Did you already resolve your issue? Hello?
