### ISSUE TITLE
No direkt vcd vm modules available!

### ISSUE THREAD

**Issue by sgutermann** [vmware/ansible-module-vcloud-director#73]
With one of the later updates VM Ware has finally made it possible to create VMs without having to use the vapp wrapper.

Have been waiting for this for quite a while now. 

Now there are no ansible modules for this at all. Everything is made around the strange vapp.

Is this in planing or being worked on?

No good releasing something great and new when you can not use it.

**Comment by mukultaneja** [comment]
@sgutermann would be helpful if you elaborate the feature a little.

**Comment by mukultaneja** [comment]
@sgutermann, I believe Pyvcloud has only one single approach so far to add VMS into an existing vApp. I think it would be better to wait for them to implement this functionality.

**Comment by sgutermann** [comment]
Thank you for checking. Now that you mention it I will have a look at pyvcloud to see if they got this on their path.

**Comment by mukultaneja** [comment]
sure. I am closing this issue then and feel free to open if you find some other insight.
