### ISSUE TITLE
Supported VCD version with these Ansible Modules

### ISSUE THREAD

**Issue by monadhiman** [vmware/ansible-module-vcloud-director#75]
Hi Team,

Could anyone confirm which VCD version is supported with these modules. As I started with VCD version 9.5 and now my playbook is not working for vcd version 8.2.

Is there anything I am missing on. Or do these modules support on VCD version 8.2 ?

Thank You.

**Comment by mukultaneja** [comment]
@monadhiman these modules expect VCD version 9.1 and above.

**Comment by monadhiman** [comment]
@mukultaneja Thanks for your reply on this. 
I know would be a silly question still, Is there any option or way to use these modules on VCD version 8.2.

**Comment by mukultaneja** [comment]
No, these modules are not compatible with 8.2.

**Comment by monadhiman** [comment]
@mukultaneja Thanks for your help !

**Comment by monadhiman** [comment]
@mukultaneja Do we have any ansible module for vCD version 8.2 ?

**Comment by mukultaneja** [comment]
Unfortunately not :(

**Comment by mukultaneja** [comment]
@monadhiman could you please close this issue?
