### ISSUE TITLE
Ansible Tower 3.5 and Python 3

### ISSUE THREAD

**Issue by pmedilall** [vmware/ansible-module-vcloud-director#76]
We currently trying to use this module on the latest version of Ansible Tower with Python 3 which is required for this module but we are unable get Tower working as in the Web front end fails to load up. 

Are there any suggestions and have you seen this problem before?

Thanks

**Comment by mukultaneja** [comment]
No, I have not seen any such problem before. Maybe it will help if you can give more detail about how you are using these modules using Ansible Tower etc.

**Comment by shamaljayalath** [comment]
We installed Ansible tower on a RHEL8 system (uses python 3 by default) and it worked.

**Comment by mukultaneja** [comment]
@shamaljayalath perfect! Please allow me to close this issue and feel free to reopen it if you find any concerns again in the future.
