### ISSUE TITLE
vcd_org fails to create Org

### ISSUE THREAD

**Issue by shamaljayalath** [vmware/ansible-module-vcloud-director#77]
We are trying to create a fresh org on vcd. AS per the documentation ( https://github.com/vmware/ansible-module-vcloud-director/blob/master/docs/index.md#org-example-usage ) all we need is org_name, full_name and is_enabled.

Since we are trying to create the org, it make sense to ask for org name (org_name)  but no point of requesting to specifying  an org. When we comment out "org" or "env_org" from main.yml , it complains not able to login to Org "none"

My roles/org/tasks/main.yml file looks like this.
-----
- name: create org
  vcd_org:
    #   user: administrator
    #   password: AnsibleLab1!
    #   host: mel-lab-vcd01
    #   org: test
       org_name: "test"
       full_name: "test"
       is_enabled : "true"
       state: "present"
  register: output

----

line 49, in login\nansible.module_utils.vcd_errors.VCDLoginError: Login failed for user Administrator to org None\n",

Any help is appreciated.

Cheers,

**Comment by mukultaneja** [comment]
@shamaljayalath, creating a new org is an administrative operation. To create a new org, one has to login to into VCD's administrative org. Here `org_name` refers to the newly org name where `env_org` / `org` refers to the VCD administrative org.

**Comment by shamaljayalath** [comment]
Thanks, heap for the response and I can confirm that resolved the issue.I Noticed someone else also had similar issue in the past and but resolved later on so perhaps we can mention that in the documentation bit more clearly so people won't run into the same issue.

For everyone else's benifit :

Use env variables to auth to VCloud Director as administrator :

env_user: administrator
    env_password: xx
    env_host: mel-lab-vcdxx
    env_org: System

Then use user/main.yml  👍 

--- 

- name: create user
  no_log: False
  vcd_user:
    username: "{{ org_admin_user }}"
    userpassword: "{{ org_admin_user_password }}"
    org_name: MyOrg  --------------------------------------> User will be created under this Org
    role_name: Organization Administrator
    full_username: MyorgAdmin
    description: Myorg Admin
    is_enabled: true
    stored_vm_quota: 30
    deployed_vm_quota: 20
    is_default_cached: true
    state: present
  register: output

---

Thanks. I will close this Bug and thanks again for your help!

Cheers,
Frank
