### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by shamaljayalath** [vmware/ansible-module-vcloud-director#78]
TASK [vdc : create vdc] *************************************************************************************************************************************
task path: /var/lib/awx/projects/_8__vcd_test/roles/vdc/tasks/main.yml:5
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: awx
<127.0.0.1> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1567750851.3354096-80875269469913 `" && echo ansible-tmp-1567750851.3354096-80875269469913="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1567750851.3354096-80875269469913 `" ) && sleep 0'
Using module file /var/lib/awx/projects/_8__vcd_test/modules/vcd_org_vdc.py
<127.0.0.1> PUT /var/lib/awx/.ansible/tmp/ansible-local-6817x96bvj2f/tmpml8m2_4d TO /var/lib/awx/.ansible/tmp/ansible-tmp-1567750851.3354096-80875269469913/AnsiballZ_vcd_org_vdc.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1567750851.3354096-80875269469913/ /var/lib/awx/.ansible/tmp/ansible-tmp-1567750851.3354096-80875269469913/AnsiballZ_vcd_org_vdc.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'env_user=administrator env_password='"'"'AnsibleLab1!'"'"' env_host=mel-lab-vcd01 env_api_version=32.0 env_verify_ssl_certs=False /usr/libexec/platform-python /var/lib/awx/.ansible/tmp/ansible-tmp-1567750851.3354096-80875269469913/AnsiballZ_vcd_org_vdc.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1567750851.3354096-80875269469913/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_vcd_org_vdc_payload_yfz6hsjk/ansible_vcd_org_vdc_payload.zip/ansible/module_utils/vcd.py\", line 45, in login\n  File \"/var/lib/awx/.local/lib/python3.6/site-packages/pyvcloud/vcd/client.py\", line 888, in set_credentials\n    raise VcdException('Login failed.')\npyvcloud.vcd.exceptions.VcdException: Login failed.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1567750851.3354096-80875269469913/AnsiballZ_vcd_org_vdc.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1567750851.3354096-80875269469913/AnsiballZ_vcd_org_vdc.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-tmp-1567750851.3354096-80875269469913/AnsiballZ_vcd_org_vdc.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib64/python3.6/imp.py\", line 235, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib64/python3.6/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 618, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_vcd_org_vdc_payload_yfz6hsjk/__main__.py\", line 456, in <module>\n  File \"/tmp/ansible_vcd_org_vdc_payload_yfz6hsjk/__main__.py\", line 435, in main\n  File \"/tmp/ansible_vcd_org_vdc_payload_yfz6hsjk/__main__.py\", line 290, in __init__\n  File \"/tmp/ansible_vcd_org_vdc_payload_yfz6hsjk/ansible_vcd_org_vdc_payload.zip/ansible/module_utils/vcd.py\", line 31, in __init__\n  File \"/tmp/ansible_vcd_org_vdc_payload_yfz6hsjk/ansible_vcd_org_vdc_payload.zip/ansible/module_utils/vcd.py\", line 49, in login\nansible.module_utils.vcd_errors.VCDLoginError: Login failed for user administrator to org POrg\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

My main.yml looks like this and it has correct username and password.

- name: create vdc
  no_log: False
  vcd_org_vdc:
    user: administrator
    password: ****
    host: mel-lab-vcd01
    org: "POrg"
    vdc_name: "POrg-VDC"
    provider_vdc_name: "xxx-lab-pcdv01"
    description: "test vdc"
    allocation_model: "AllocationPool"
    is_enabled: "true"
    verify_ssl_certs: "false"
    storage_profiles:
      - name: "*(Any)"
        enabled: true
        units: "MB"
        limit: 50000
        default: true
    state: "present"
  register: output

- name: create vdc output
  debug:
    msg: '{{ output }}'

---
- name: vCloudDirectorAnsible
  hosts: localhost
  environment:
    env_user: administrator
    env_password: AnsibleLa***
    env_host: xxx-lab-vcd01
 #   env_org: Terraform
    env_api_version: 32.0
    env_verify_ssl_certs: false
  roles:
      - vdc

We tried both api version 30 and 32 but no luck.

Any idea ?

**Comment by mukultaneja** [comment]
@shamaljayalath which org you want to login into Terraform or POrg? Please share your VCD version and Pyvcloud version.

**Comment by kaneda-fr** [comment]
Is your user a system admin or an org admin?

The log shows it’s a user authentication issue.
« Login failed for user administrator to org »

Try creating a .org admin sur account and use this in your ansible script (system admin can’t log into an org)

**Comment by shamaljayalath** [comment]
thanks for the update.

I guess what's not very clear is the usage of env_variables to authenticate to the VCD. Use system user to auth as Administrator.

-----  

- name: vCloudDirectorAnsible
  hosts: localhost
  environment:
    env_user: administrator
    env_password: xxxx
    env_host: mel-lab-vcdxxxxx
    env_org: System
    env_api_version: 32.0
    env_verify_ssl_certs: false

---

Keep up the good works guys ! I shall close this Bug now.
