### ISSUE TITLE
RFE: Would it be possible to add capability to create portgroup,external network and VDC network

### ISSUE THREAD

**Issue by shamaljayalath** [vmware/ansible-module-vcloud-director#79]
Greetings,

Would it be possible to Add the following functionality to this module?

- First Create a Port Group at VCenter level using the module.
- Secondly, create an external network linked to the port group with network info.
- Lastly, create VDC org network and link to the external network.

Currently we have to use various other tooling to achive this but if this can be included in this module, that woyuld be fantastic!

Keep up the good work guys!

**Comment by mukultaneja** [comment]
@shamaljayalath I have added a new module to manage vCD External Networks  89798fb53e54a215676fc34fdf10501322251823

**Comment by shamaljayalath** [comment]
Fantastic work @mukultaneja ! 

Just wondering if you are also thinking of working on a module for creating "ORG VDC network" which will link back to the External network? That will complete the whole network  requirements.

Thanks Again!

**Comment by mukultaneja** [comment]
@shamaljayalath, we already had a module to manage the Org VDC network (isolated /direct/routed). I just made some structural modification in the module and added a new patch 570dd4d4a723925fa89352f71202bf19bfc8bf16. Please take a look!

**Comment by mukultaneja** [comment]
@shamaljayalath, about feature request to create vCenter Port Groups through these modules, I do not think we can create vCenter Port groups using pyVcloud as of now.

**Comment by shamaljayalath** [comment]
That looks fantastic! Thanks for that! I will let you know when I get around to testing the module.

In terms of the port Groups, If that's an issue happy to use other Ansible module (vmware_dvs_portgroup) to create the port Group. I just thought I might suggest that for completeness so the whole use cases ( On-Boarding new tenant) can be achieved via the same module.

Anyways good work @mukultaneja!

**Comment by mukultaneja** [comment]
@shamaljayalath I have just started new projects to automate vCenter setup and management
https://github.com/mukultaneja/ansible-modules-vCenter-automation
https://github.com/mukultaneja/vCenter-automation-ansible-playbooks

Please take a look and support if you would like.
Please close this issue if you don't have any more concerns.

**Comment by shamaljayalath** [comment]
Sounds good! Thanks for letting me know. I'll close this now.
