### ISSUE TITLE
unable to get authenticated.

### ISSUE THREAD

**Issue by hussainaphroj** [vmware/ansible-module-vcloud-director#93]
Dear Team,

I am trying to setup it first time getting "Vm element not found" error, I tried with both python2 and python 3 and ansible 2.9.2 but still no luck.

vcd.yml
-------
---
- name: vCloudDirectorAnsible
  hosts: localhost
  environment:
    env_user: "testuser"
    env_password: "test@123"
    env_host: "https://1.2.3.4/"
    env_org: "system"
    env_api_version: 30.0
    env_verify_ssl_certs: false
  tasks:
    - name: create vapp
      vcd_vapp:
        vapp_name: "test_vapp_1"
        vdc: "TestOrgVdc"
        power_on: False
        state: "present"
      register: output
 
error details:

PLAY [vCloudDirectorAnsible] ***********************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
task path: /etc/ansible/vcd.yml:4
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1578573083.11-154990387544876 `" && echo ansible-tmp-1578573083.11-154990387544876="` echo /root/.ansible/tmp/ansible-tmp-1578573083.11-154990387544876 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/setup.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-2278vdsVTj/tmp354wXC TO /root/.ansible/tmp/ansible-tmp-1578573083.11-154990387544876/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1578573083.11-154990387544876/ /root/.ansible/tmp/ansible-tmp-1578573083.11-154990387544876/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'env_verify_ssl_certs=False env_user=testuser env_api_version=30.0 env_org=system env_host=https://1.2.3.4/ env_password=test@123 /usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1578573083.11-154990387544876/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1578573083.11-154990387544876/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [create vapp] *********************************************************************************************************************************************************
task path: /etc/ansible/vcd.yml:14
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1578573085.3-39249108363540 `" && echo ansible-tmp-1578573085.3-39249108363540="` echo /root/.ansible/tmp/ansible-tmp-1578573085.3-39249108363540 `" ) && sleep 0'
Using module file /etc/ansible/ansible-module-vcloud-director/modules/vcd_vapp.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-2278vdsVTj/tmpNh2nIl TO /root/.ansible/tmp/ansible-tmp-1578573085.3-39249108363540/AnsiballZ_vcd_vapp.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1578573085.3-39249108363540/ /root/.ansible/tmp/ansible-tmp-1578573085.3-39249108363540/AnsiballZ_vcd_vapp.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'env_verify_ssl_certs=False env_user=testuser env_api_version=30.0 env_org=system env_host=https://1.2.3.4/ env_password=test@123 /usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1578573085.3-39249108363540/AnsiballZ_vcd_vapp.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1578573085.3-39249108363540/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1578573085.3-39249108363540/AnsiballZ_vcd_vapp.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1578573085.3-39249108363540/AnsiballZ_vcd_vapp.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1578573085.3-39249108363540/AnsiballZ_vcd_vapp.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.vcd_vapp', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_vcd_vapp_payload_f9cMbB/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py", line 171, in <module>
  File "/root/.local/lib/python2.7/site-packages/pyvcloud/vcd/org.py", line 1863
    raise EntityNotFoundException(f"Vm element not found")
                                                        ^
SyntaxError: invalid syntax

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1578573085.3-39249108363540/AnsiballZ_vcd_vapp.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1578573085.3-39249108363540/AnsiballZ_vcd_vapp.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1578573085.3-39249108363540/AnsiballZ_vcd_vapp.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.vcd_vapp', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_vcd_vapp_payload_f9cMbB/ansible_vcd_vapp_payload.zip/ansible/modules/vcd_vapp.py\", line 171, in <module>\n  File \"/root/.local/lib/python2.7/site-packages/pyvcloud/vcd/org.py\", line 1863\n    raise EntityNotFoundException(f\"Vm element not found\")\n                                                        ^\nSyntaxError: invalid syntax\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

Any help will be appreciated.

**Comment by crapulent** [comment]
Hi
today I've got the same error
and changing ansible interpreter to python3 helped me
(ansible installed from default packet on my version of ubuntu uses python2 by default, so I did
`pip3 install --user pyvcloud` and appended `interpreter_python = /usr/bin/python3` line to `ansible.cfg` from this repo)

What is the error when you are using python3? (I see python2 in your log output)

**Comment by mukultaneja** [comment]
@hussainaphroj pre-requisites for using these ansible modules are VCD version >= 9.0 and python3. Please confirm if you are running these modules against the above pre-requisites.
