### ISSUE TITLE
Can't add network to vapp with module vapp "Value of unknown type: <class 'AttributeError'>, no such child"

### ISSUE THREAD

**Issue by ndalbroi** [vmware/ansible-module-vcloud-director#96]
Good afternoon,

I am having an issue trying to add a network to a vapp while using the module vapp.  When I add the parameter "network" I get that error. My playbook looks like this:

- name: create vapp vm nic
  vcd_vapp_vm_nic:
     vm_name: "test"
     vapp: "test"
     vdc: "VDC"
     network: "NETWORK"
     ip_allocation_mode: "MANUAL"
     state: "present"
     nic_id: "0"
     ip_address: 192.168.1.0
  register: output

Any help will be appreciated

**Comment by rmharwood** [comment]
This is exactly the same as issue #87

**Comment by ndalbroi** [comment]
Clossing the issue.
