### ISSUE TITLE
vappvmnic not creating additional network

### ISSUE THREAD

**Issue by ndalbroi** [vmware/ansible-module-vcloud-director#97]
Dear Team,

I am having issues generating a second network with the role vappvmnic. When I'm tyring to add the network I get a message "the vcd entity  does not exist". Is there any solution or workaround to this?

Thanks in advance.

Regards

**Comment by mukultaneja** [comment]
@ndalbroi would be helpful if share more information on the issue like execution logs might help to understand more.
